feat: P2022-93 Configure i18next (translations)
intive/patronage22_szczecin_js pull request #10
Opened 2022-01-20 23:18 UTC by yusts

2022-01-21 09:36 UTC, alexsimkovich requested changes

2022-01-21 09:36 UTC, alexsimkovich commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
PLease remove this file and add it to`.gitingore` file

2022-01-21 09:36 UTC, alexsimkovich commented on public/locales/en/common.json
> +{
Let's assume that `common.json` file will have common translations which are repeating on each page (footer, header, etc.). 
Also please create something meaningful, not just `p` :)
Please format json file properly

2022-01-21 09:37 UTC, alexsimkovich commented
@yusts in general, looks good.

2022-01-23 20:17 UTC, yusts commented
@alexsimkovich @lukasz-galka 
Thanks for your comments. I already pushed the updated version.

2022-01-24 09:27 UTC, lukasz-galka approved these changes

2022-01-24 09:28 UTC, merged