feat: P2022-62 Add header component
intive/patronage22_szczecin_js pull request #12
Opened 2022-01-21 19:33 UTC by karosmyr

2022-01-22 11:05 UTC, lukasz-galka requested changes

2022-01-22 11:05 UTC, lukasz-galka commented on components/Header/style.js
> +  margin-left: 0.688rem;
figma czasami moze wprowadzic w blad jak sprawdzasz odleglosci ikonek i tak pokazuje tutaj 11px
![image](https://user-images.githubusercontent.com/17024927/150635854-9543a696-1cbd-4251-a632-948bf8bae167.png)

jednak ikonki powinny byc wpisane w box 24x24 px, zobacz ponizej
![image](https://user-images.githubusercontent.com/17024927/150635872-5cd6189c-f3eb-47d6-ac33-eea5c5d1e2ad.png)

w tym pabelu po lewej wybrany jest inny element, i teraz pokazuje prawidłowo 8px

2022-01-22 11:05 UTC, lukasz-galka commented on styles/global.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');
pobieranie fonta wolalbym miec w sekcji `head`

2022-01-24 09:52 UTC, alexsimkovich commented on components/Header/Header.js
> +        <HeaderTitleText>My Retro Board</HeaderTitleText>
translation configuration was already merged. Please add this text to the translation json and use here a `t()` function

2022-01-24 09:52 UTC, alexsimkovich commented on components/Header/style.js
> +`
I don't see breakpoints for `desktop` view. As far as i know, the width of the container on desktop should be `max-width: 1440px` !?

2022-01-24 09:52 UTC, alexsimkovich commented on components/Layout/style.js
> +  max-width: 1400px;
Shouldn't it be
```
max-width: 1440px;
padding-left: 12px;
padding-right: 12px;
```
?

2022-01-25 16:56 UTC, lukasz-galka requested changes

2022-01-25 16:56 UTC, lukasz-galka commented on public/locales/en/common.json
> +}
jako, ze juz uzywasz kluczy w hederze to możemy skasowac ten klucz `next-i18next-example-key` z tego pliku i rowniez jego użycie na stronie glownej, tak samo z ikonkami, mamy już je w hederze wiec nie musimy ich trzymac na stronie glownej w main. wiec skasuj chwilowo to co mamy w main, niedlugo zmegujemy zmiany od Jacka i wpadnie tam pierwszy board tile :)

2022-01-25 16:56 UTC, lukasz-galka commented on pages/index.page.js
> +        <link rel='preconnect' href='https://fonts.googleapis.com' />
jeżeli chcemy miec te preconnect to daj je przed material icons

2022-01-25 16:56 UTC, lukasz-galka commented on components/Layout/style.js
> +`
chcialbym aby header i main, miały na starcie padding poziomy 5%, a od 1440px 2.5rem, dzieki temu bedziemy mogli miec ten sam layout na stronie glownej i w detalach, kasujemy max-width z headera/wrappera

ta przerwe planowalem zrobic w https://tracker.intive.com/jira/browse/P2022-66 
![image](https://user-images.githubusercontent.com/17024927/151019817-f5749a31-192d-4478-bb12-cc3b630474f9.png)

2022-01-26 14:00 UTC, alexsimkovich requested changes

2022-01-26 14:00 UTC, alexsimkovich commented on public/locales/en/common.json
> +  "header-title": "My Retro Board"
i guess for json files it is better to have prop. names in camelCase
i.e "headerTitle"

2022-01-26 14:03 UTC, alexsimkovich requested changes

2022-01-26 14:03 UTC, alexsimkovich commented on components/Header/Header.js
> +}
1. In most cases, icon and logo should be clickable (should be a link with `href='/'`)
2. Header component should accept some props with a header text instead of statically put the text inside

2022-01-28 13:35 UTC, lukasz-galka approved these changes

2022-01-28 13:37 UTC, lukasz-galka approved these changes

2022-01-28 13:57 UTC, merged