feat: P2022-63 Add button component
intive/patronage22_szczecin_js pull request #13
Opened 2022-01-23 02:57 UTC by Noshi96

@lukasz-galka
@alexsimkovich

2022-01-24 10:07 UTC, alexsimkovich requested changes

2022-01-24 10:07 UTC, alexsimkovich commented on components/Button/Button.js
> +  )
A lot of redundant code...
Check this
```
  return (
    <StyledButton type={props.type}>{props.title}</StyledButton>
  )
```

in your `style.js` file differentiate styles based on the button `type` prop:
Example:
```
const StyledButton = styled.button`
  background-color: ${props => props.type === 'contained' ? 'black : 'transparent'};
  etc...
`
```

2022-01-24 23:42 UTC, Noshi96 commented on components/Button/Button.test.js
> +})
Should I also check by toHaveAttribute if name= and type= presents? 
For example:
```javascript
  it('renders contained disabled button with icon', () => {
    const container = render(<Button type='contained' name='crop_original' disabled>New board</Button>)
    expect(container.container).toMatchSnapshot()
    expect(container.getByRole('button')).toHaveAttribute('name')
    expect(container.getByRole('button')).toHaveAttribute('type')
    expect(container.getByRole('button')).toHaveAttribute('disabled')
    expect(container.getByRole('button')).toBeDisabled()
  })
```

2022-01-25 00:26 UTC, Noshi96 commented on components/Button/Button.js
> +  )
Fixed

2022-01-25 00:27 UTC, Noshi96 commented on components/Button/Button.js
> +  const internalElements = (
Changed

2022-01-25 00:28 UTC, Noshi96 commented on components/Button/Button.test.js
> +    expect(tree.container).toMatchSnapshot()
Changed

2022-01-25 00:28 UTC, Noshi96 commented on components/Button/Button.test.js
> +  it('renders blank disabled button without icon', () => {
Done

2022-01-26 06:33 UTC, lukasz-galka requested changes

2022-01-26 06:33 UTC, lukasz-galka commented on components/Button/__snapshots__/Button.test.js.snap
> +exports[`Buttons renders button with icon 1`] = `
why so many items/children?

button without icon should have structure like
```
<button>text</button>
```

and button with icon
```
<button><span>icon</span>text</button>
```

2022-01-26 06:33 UTC, lukasz-galka commented on components/Button/style.js
> +`
update structure for button as I wrote above and rewrite styles - button is really simple element and I see a lot of styles...

2022-01-26 06:33 UTC, lukasz-galka commented on components/Button/Button.js
> +      {props.name
use `icon` istead `name`

2022-01-26 06:33 UTC, lukasz-galka commented on components/Button/Button.test.js
> +    const container = render(<Button type='contained' name='crop_original'>New board</Button>)
here you should have name of component, like `const button = render....`

2022-01-26 06:33 UTC, lukasz-galka commented on components/Button/Button.test.js
> +describe('Buttons', () => {
here you should have name of component, so `Button`

2022-01-26 06:33 UTC, lukasz-galka commented on components/Button/style.js
> +  color: ${(props) => (props.type === 'contained' ? '#FFFFFF' : '#515151')};
what if there will be third type? you should define one as default (I would go with contained, because it will be used more often) and then override it when different type is used

2022-01-26 06:33 UTC, lukasz-galka commented on components/Button/style.js
> +  color: ${(props) => (props.type === 'contained' ? '#FFFFFF' : '#515151')};
you can't set background to white for type text, it should be just transparent

2022-01-26 13:59 UTC, alexsimkovich commented on components/Button/Button.test.js
> +})
yes, you can check

2022-01-29 14:14 UTC, lukasz-galka requested changes

2022-01-29 14:14 UTC, lukasz-galka commented on components/Button/style.js
> +
chcialbym abys napisal stule od buttona tak jak w przykladzie tutaj https://styled-components.com/

czyli najpierw definiujesz domyslny styl dla buttona, u nas `contained` a potem zadpisujesz je dla stylu `text`, potem dojdzie trzeci typ `outline`, bedzie dzieki temu mozna go latwo dodac

```
import styled, { css } from 'styled-components'

export const StyledButton = styled.button`
  // here define styles for contained button, it is our default one
  background: red;

  // here define customization for "text" type
  ${props => props.type === 'text' && css`
    background: yellow;
  `}
`

```

2022-01-29 14:14 UTC, lukasz-galka commented on components/Button/Button.js
> +  const { type = 'contained' } = props
nie potrzebujemy tego, poniewaz nie sprawdzamy juz `contained` w stylach, to nasz domyslny button

2022-01-29 14:14 UTC, lukasz-galka commented on components/Button/style.js
> +  font-family: Roboto;
roboto to jest domyslny font, wiec nie muszi go definiowac tutaj

2022-01-29 14:14 UTC, lukasz-galka commented on components/Button/style.js
> +  span {
nie styluj po tagu, ostyluj tutaj nasz komponent Icon

2022-01-29 14:14 UTC, lukasz-galka commented on components/Button/style.js
> +  border: ${(props) => (props.type === 'contained' ? '1px solid #515151' : '1px solid transparent')};
po co mu border? jezeli chcesz skasowac domyslny od pregladarki to daj `border: none`

2022-01-29 19:48 UTC, Noshi96 commented on components/Button/style.js
> +
Mam pytanie odnośnie użycia komponentu, tworząc style tak jak teraz mi napisałeś mogę zrobić coś takiego:
 plik: index.page.js
 ```javascript
 <Button text>Continue</Button>
 ```
 plik: Button.js
 ```javascript
   return (
    <StyledButton
      onClick={props.onClick}
      disabled={props.disabled}
      onlyIcon={onlyIcon}
      {...props}
    >
      {buttonContent}
    </StyledButton>
  )
 ```
Przekazując pozostałe propsy za pomocą `{...props}` nie muszę pisać `type=''` wywołując button, pytanie czy jest to dobre podejście i czy nie lepiej zostać przy  `<Button type='text'>Continue</Button>` w pliku index.page.js i type={props.type} w pliku Button.js?

2022-01-30 14:16 UTC, AnnaSawickaZiolkowska commented on components/Button/style.js
> +  }
czy tutaj nie będzie lepszym rozwiązaniem `cursor: not-allowed;`?

2022-01-30 15:51 UTC, Noshi96 commented on components/Button/style.js
> +  }
Nie było co do tego wytycznych, ale faktycznie `cursor: not-allowed; ` wygląda lepiej :D

2022-01-31 18:17 UTC, lukasz-galka requested changes

2022-01-31 18:17 UTC, lukasz-galka commented on components/Button/__snapshots__/Button.test.js.snap
> +    <div
po co ten div? zrob bez niego

2022-01-31 18:17 UTC, lukasz-galka commented on components/Button/style.js
> +  color: #FFFFFF;
pokazuje te przerwy w stylach

```
  border: none;
  cursor: pointer;
  height: 2.5rem;
  display: flex;
  align-items: center;
  background: #515151;
  border-radius: 8px;
```

2022-01-31 18:17 UTC, lukasz-galka commented on components/Button/style.js
> +
tak jak jest teraz jest ok

2022-01-31 18:17 UTC, lukasz-galka commented on components/Button/style.js
> +  ${props => props.outline && css`
skasuj chwilowo outline, ktos doda go sobie jak bedzie potrzeba

2022-01-31 18:17 UTC, lukasz-galka commented on components/Button/style.js
> +export const StyledIcon = styled.div`
tutaj daj style na nasz komponent Icon

2022-01-31 18:17 UTC, lukasz-galka commented on components/Button/Button.js
> +  const onlyIcon = (typeof props.children === 'undefined')
potrzebujemy taka opcje teraz? ja nie widze aktualnie takiej potrzeby wiec bym to skasowal

2022-01-31 23:12 UTC, Noshi96 commented on components/Button/style.js
> +export const StyledIcon = styled.div`
Dosyć mocno się zblokowałem próbując właśnie pozbyć się tego `diva` na rzecz stylowania naszego `Icon`. 
Wydaje mi się, że mamy pewien bug w componencie Icon.js:
Wersja z maina:
```javascript
const Icon = ({ name }) => {
  return <span className='material-icons'>{name}</span>
}

export default Icon
```
Wersja, w której można stylować component Icon:
```javascript
const Icon = (props) => {
  return <span className={`material-icons ${props.className}`}>{props.name}</span>
}

export default Icon
```
Mój plik style.js dla Button.js:
```javascript
const MaterialIcon2 = (props) => (
  <span className={`material-icons ${props.className}`}>{props.icon}</span>
)

const MaterialIcon3 = (props) => (
  <Icon name={props.icon} className={`material-icons ${props.className}`} />
)

export const StyledIcon2 = styled(MaterialIcon2)`
  margin-right: 0.25rem;
  color: pink;
`
export const StyledIcon3 = styled(MaterialIcon3)`
  margin-right: 0.25rem;
  color: yellow;
`
```
Przykład użycia w pliku Button.js:
```javascript
<StyledIcon2 icon={props.icon} />
```

 StyledIcon2 działa, a StyledIcon3 działa tylko wtedy jak zmienimy plik Icon.js.
Wydaje mi się, że może to mieć związek z tym co można przeczytać w dokumentacji do styled-components, a konkretnie
"The styled method works perfectly on all of your own or any third-party component, as long as they attach the passed className prop to a DOM element."[SOURCE](https://styled-components.com/docs/basics#styling-any-component), a u nas w Icon nie było props.className.

2022-02-01 15:25 UTC, lukasz-galka requested changes

2022-02-01 15:55 UTC, Noshi96 commented on components/Header/style.js
> +  text-decoration: none;
Chyba z maina, ja nic w Headerze nie ruszałem

2022-02-01 16:58 UTC, Noshi96 commented on components/Button/style.js
> +export const StyledIcon = styled.div`
Okej zrobione

2022-02-02 06:38 UTC, lukasz-galka requested changes

2022-02-02 06:38 UTC, lukasz-galka commented on components/Button/style.js
> +const MaterialIcon = (props) => (
skoro naprawiles juz `Icon` to po co tutaj ten `MaterialIcon` ?

2022-02-02 06:38 UTC, lukasz-galka commented on components/Button/style.js
> +export const StyledIcon = styled(MaterialIcon)`
styluj juz na poprawionym `Icon`

2022-02-02 06:38 UTC, lukasz-galka commented on components/Header/style.js
> +  text-decoration: none;
no ale jak one sa z `main` to nie powinny byc widoczne u Ciebie jako zmiana, zrob rebase

2022-02-02 10:39 UTC, Noshi96 commented on components/Button/style.js
> +export const StyledIcon = styled(MaterialIcon)`
Okej poprawione

2022-02-02 10:48 UTC, alexsimkovich commented on components/Button/Button.js
> +import React from 'react'
This is redundant. It is imported by next by default

2022-02-02 11:51 UTC, alexsimkovich approved these changes

2022-02-03 06:11 UTC, lukasz-galka approved these changes

2022-02-03 06:11 UTC, merged