feat: P2022-150 Add board header component
intive/patronage22_szczecin_js pull request #14
Opened 2022-01-26 14:50 UTC by AnnaSawickaZiolkowska

2022-01-29 13:21 UTC, lukasz-galka requested changes

2022-01-29 13:21 UTC, lukasz-galka commented on components/BoardHeader/styled.js
> +.return-link {
ostyluj link

```
export const StyledLink = styled.a`
...
`
```

i potem

```
<Link href='/' passHref><StyledLink>Return to main board</StyledLink></Link>
```

2022-01-29 13:21 UTC, lukasz-galka commented on components/BoardHeader/styled.js
> +export const Title = styled.p`
wykorzystaj tutaj `h1`

2022-01-29 13:21 UTC, lukasz-galka commented on components/BoardHeader/styled.js
> +font-size: 2.25rem;
potrzebujesz te style?
```
all: unset;
min-width: 223px;
font-family: Roboto;
font-style: normal;
font-weight: normal;
```

2022-01-29 13:21 UTC, lukasz-galka commented on components/Layout/Layout.js
> +      <BoardHeader title={t('boardHeaderTitle')} />
nie potrzebujemy `boardHeaderTitle` w kluczach od translacji, poniewaz on bedzie dynamiczny, w zaleznosci jakie detale otworzymy

2022-01-29 16:17 UTC, AnnaSawickaZiolkowska commented on components/BoardHeader/styled.js
> +gap: 10px;
![Zrzut ekranu 2022-01-29 o 17 11 57](https://user-images.githubusercontent.com/77212945/151668489-eab503e1-f2c6-419f-a35b-adad28cdc124.png)
![Zrzut ekranu 2022-01-29 o 17 13 17](https://user-images.githubusercontent.com/77212945/151668491-bc960b71-a29d-4e82-b2df-334d10d0c970.png)

2022-01-29 16:18 UTC, AnnaSawickaZiolkowska commented on components/BoardHeader/styled.js
> +gap: 10px;
24px czyli 1.5rem

2022-01-29 16:39 UTC, AnnaSawickaZiolkowska commented on components/BoardHeader/styled.js
> +font-size: 2.25rem;
w zasadzie tylko `font-weight: normal;`
zapomniałam to usunąć po rebase z main.

2022-01-30 14:40 UTC, AnnaSawickaZiolkowska commented on components/BoardHeader/styled.js
> +min-height: 120px;
w figmie frame ma `height: 120px;`, 
nie chciałam na sztywno dodawać wysokości, żeby dostosowywała się do mobilnego wyglądu. Poszczególne elementy mają wysokość tylko taką jaką potrzebują. Więc jak usunę `min-height: 120px;` to na desktopie wysokość frame robi mi się 114px, 
mogę ustawić `gap: 16px;` zamiast `gap: 10px;`, ale wtedy na mobilce te dodatkowe 6px jest chyba niepotrzebne

2022-02-02 07:37 UTC, lukasz-galka commented on public/locales/en/common.json
> +  "headerTitle": "My Retro Board",
jezeli jakies klucze naleza do jednego tematu, to mozemy je grupowac

```
"boardHeader": {
  "returnLink": "...",
  "button": ...
}
```

2022-02-02 07:37 UTC, lukasz-galka commented on components/BoardHeader/styled.js
> +gap: 10px;
@AnnaSawickaZiolkowska mi chodzilo o `gap` ktore masz na `10px`

![image](https://user-images.githubusercontent.com/17024927/152112552-0037abcd-60fb-43b1-a7b3-21e16968caa5.png)

2022-02-02 07:42 UTC, lukasz-galka requested changes

2022-02-02 07:42 UTC, lukasz-galka commented on components/BoardHeader/BoardHeader.js
> +      <Link href='/' passHref><StyledLink>{props.returnLink}</StyledLink></Link>
`returnLink` oraz `buttonLink` sugeruja mi ze te propsy sa odpowiedzialne za przekazanie linku, a nie tekstu... zmien na cos innego

2022-02-02 07:42 UTC, lukasz-galka commented on components/BoardHeader/BoardHeader.js
> +        <button>{props.buttonLink}</button>
bedziemy potrzebowac jakis trigger na ten button, wiec komponent powinien przyjac jakas funkcje jak `onActionClick` i sprawdz czy ona sie wywyoluje w testach

2022-02-02 07:42 UTC, lukasz-galka commented on components/BoardHeader/BoardHeader.js
> +      <Link href='/' passHref><StyledLink>{props.returnLink}</StyledLink></Link>
moze `navigationText` oraz `actionText` ?

2022-02-06 10:12 UTC, lukasz-galka requested changes

2022-02-06 10:12 UTC, lukasz-galka commented on components/BoardHeader/BoardHeader.test.js
> +    const { container } = render(<BoardHeader returnLink='returnLink' buttonLink='buttonLink' title='title' handleNewColumn={mockOnClick} />)
potrzebujesz wyciagac `container` ?

2022-02-06 10:12 UTC, lukasz-galka commented on components/BoardHeader/BoardHeader.test.js
> +    expect(container).toMatchSnapshot()
snapshot sprawdzamy juz w poprzednim tescie, tutaj nie ma juz takiej potrzeby

2022-02-06 10:12 UTC, lukasz-galka commented on components/BoardHeader/BoardHeader.test.js
> +    // expect(container.baseElement).toMatchSnapshot()
skasuj komentarze

2022-02-06 10:12 UTC, lukasz-galka commented on components/BoardHeader/BoardHeader.test.js
> +    const { container } = render(<BoardHeader returnLink='returnLink' buttonLink='buttonLink' title='title' handleNewColumn={mockOnClick} />)
`returnLink`? czy moze `returnLinkText`? sprawdz jakie parametry przekazujesz i jakie sa wykorzystywane w komponencie, zobacz czy renderuja sie poprawnie w snapshocie z pierwszego testu

2022-02-06 10:12 UTC, lukasz-galka commented on components/BoardHeader/BoardHeader.test.js
> +  it('create new column', () => {
powinna byc nowa linia pomiedzy `it`, opis `it` powinien byc `should ...` przykładowo `should trigger handler after clicking on new column button`

2022-02-06 10:12 UTC, lukasz-galka commented on components/BoardHeader/BoardHeader.js
> +        <Button onClick={props.handleNewColumn}>{props.buttonText}</Button>
propsy ktore sa funkcjami powinny zaczynac sie od `on`, przykładowo `onNewColumn`

2022-02-06 10:12 UTC, lukasz-galka commented on components/BoardHeader/style.js
> +export const Container = styled.section`
popraw formatowanie, powinno byc wciecie jak

```
export const TitleWrapper = styled.div`
  height: fit-content; 
`
```

2022-02-06 13:11 UTC, AnnaSawickaZiolkowska commented on components/BoardHeader/BoardHeader.test.js
> +    const { container } = render(<BoardHeader returnLink='returnLink' buttonLink='buttonLink' title='title' handleNewColumn={mockOnClick} />)
ale głupi błąd... zapomniałam tu zmienić, już poprawione i się wszystko ładnie renderuje w snapshocie

2022-02-07 13:03 UTC, lukasz-galka requested changes

2022-02-07 13:03 UTC, lukasz-galka commented on components/BoardHeader/BoardHeader.test.js
> +    render(<BoardHeader returnLinkText='Return to main board' buttonText='New Column' title='Board name 1' />)
It doesn't make sense to have test without `expect`, so just remove it

2022-02-07 16:10 UTC, lukasz-galka approved these changes

2022-02-09 12:24 UTC, alexsimkovich approved these changes

2022-02-21 17:30 UTC, merged