feat: P2022-64 Add create board tile
intive/patronage22_szczecin_js pull request #15
Opened 2022-01-27 20:49 UTC by grumpyjacek

2022-01-29 11:39 UTC, lukasz-galka requested changes

2022-01-29 11:39 UTC, lukasz-galka commented on components/CreateBoardTile/CreateBoardTile.js
> +}
jak teraz o tym mysle to lepiej jakaby tylko button byl klikalny :D ale juz nie zmieniajmy tego teraz, bo mamy to w AC itp

wiec, jako ze nasz tile ma dzialac jako button to bym sugerowal dac my `role="button"` oraz `tabindex="0"` aby mozna bylo go focusowac. Dzieki temu w testach tez mozesz wyszukac po roli button i nie potrzebujesz tego `testid`, dodaj 2 testy jeden na tile click i drugi na button click

2022-01-29 15:07 UTC, grumpyjacek commented on components/CreateBoardTile/style.js
> +export const Button = styled.button`
Oki, to czekam na przycisk :)

2022-01-29 15:07 UTC, grumpyjacek commented on components/CreateBoardTile/CreateBoardTile.test.js
> +import { fireEvent, render } from '@testing-library/react'
Podmienione.

2022-01-29 15:08 UTC, grumpyjacek commented on components/CreateBoardTile/CreateBoardTile.test.js
> +
Jest :)

2022-01-29 15:10 UTC, grumpyjacek commented on components/CreateBoardTile/CreateBoardTile.js
> +}
Zrobione. Rolę nazwałem inaczej (as-button), bo na razie Button jeszcze jest w kodzie i na testach był problem.

2022-01-31 13:06 UTC, lukasz-galka commented on components/CreateBoardTile/CreateBoardTile.js
> +}
@grumpyjacek tych wartosci dla `role` to nie mozemy sobie wymyslac :) musi byc `button` tutaj, w testach poszukaj wszystkie po tej roli i wybierz pierwszy dla testu od komponentu

2022-01-31 13:07 UTC, lukasz-galka commented on components/CreateBoardTile/CreateBoardTile.test.js
> +  it('clicks ob button', () => {
literowka `ob` oraz dodaj nowe linie pomiedzy `it`

2022-02-01 11:26 UTC, grumpyjacek commented on components/CreateBoardTile/CreateBoardTile.js
> +}
@lukasz-galka hmm, ok, szkoda, bo puściło z wlasną nazwą ;) poprawiłem

2022-02-01 11:26 UTC, grumpyjacek commented on components/CreateBoardTile/CreateBoardTile.test.js
> +  it('clicks ob button', () => {
poprawione

2022-02-03 20:24 UTC, grumpyjacek commented on components/CreateBoardTile/style.js
> +export const Button = styled.button`
Przycisk dodany. Nie wiem, czy to istotne, ale w stosunku do projektu na figmie pomiędzy ikoną a napisem brakuje kilku pikseli paddingu, przez co przycisk jest węższy o około 2px :)

2022-02-04 06:17 UTC, lukasz-galka commented on components/CreateBoardTile/style.js
> +export const Button = styled.button`
przerwa miedzy ikonka a tekstem jest ok, 4px 

![image](https://user-images.githubusercontent.com/17024927/152481676-a780de62-b642-4fbf-b5e8-40a81c13f5c2.png)

roznica w długsci moze wynikac z tego jak figma i web renderuja text

2022-02-04 06:18 UTC, lukasz-galka approved these changes

2022-02-04 09:19 UTC, alexsimkovich approved these changes

2022-02-07 06:30 UTC, merged