feat: P2022-346 Create modal component
intive/patronage22_szczecin_js pull request #19
Opened 2022-01-30 02:12 UTC by karosmyr

2022-02-04 09:49 UTC, alexsimkovich commented
Krótki przykład jak ja to widze:
```
function addContainer (id) {
    const rootElement = document.querySelector('#' + id)

    if (rootElement) {
      return rootElement
    }

    const element = document.createElement('div')
    element.setAttribute('id', id)
    document.body.appendChild(element)
    return element
}

function removeElement (element) {
  document.body.removeChild(element)
}

const ModalOverlay = ({ children }) => {
  useEffect(() => {
    blockScrollOnBody()
    scrollToTop()
    return () => {
      offNoScroll()
    }
  }, [])
  return <StyledModalOverlay>{children}</StyledModalOverlay>
}

const ModalOverlayPortal = ({ children }) => {
    const root = addContainer('modal-portal') // tutaj podajesz ID
    if (!root) {
      return null
    }

    useEffect(() => {
      return () => removeElement(root)
    }, [])

    return createPortal(<ModalOverlay>{children}</ModalOverlay>, root)
  } 
}
```

2022-02-04 12:04 UTC, lukasz-galka requested changes

2022-02-04 12:04 UTC, lukasz-galka commented on components/Modal/style.js
> +`
na mobilce powinna byc przerwa miedzy buttonami i nie zmienialbym ich styli, jedynie powinny byc rozciagniete, aby zajmowac cala dostepna przestrzen

2022-02-04 12:04 UTC, lukasz-galka commented on components/Modal/style.js
> +  position: absolute;
nie dawaj ikonce pozycji absolutnej, jezeli musisz ja przesunac wyzej daj jej ujemny margin top, tak samo content nie powinien miec pozycji absolute i na sztywno 80px

2022-02-04 12:09 UTC, alexsimkovich requested changes

2022-02-04 12:09 UTC, alexsimkovich commented on public/locales/en/common.json
> +  "modalTitle": "Set password",
Najlepiej, stworzyć osobny plik (namespace) np. `modals.json` i wszystkie translacje od modala opisać w tym plike, później:

```export async function getStaticProps ({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'modals'])) <---- i tak samo jeżeli na kliencie bedziesz potrzebował
    }
  }
}
```

2022-02-09 14:56 UTC, alexsimkovich requested changes

2022-02-09 14:56 UTC, alexsimkovich commented on components/Modal/ModalPortalCreator.js
> +    root.setAttribute('aria-lebelledby', 'modalTitle')
myślę że dodawanie atrybutów, które będą takie same zawsze można przenieść do funkcji `addContainer`

2022-02-09 14:56 UTC, alexsimkovich commented on components/Modal/ModalPortalCreator.js
> +export default function ModalPortalCreator (props) {
dla mnie nazwa troche dziwna. Może po prostu `<ModalPortal />`?

2022-02-09 14:56 UTC, alexsimkovich commented on components/Modal/ModalPortalCreator.test.js
> +    expect(mockOnClick).toHaveBeenCalledTimes(1)
Kiedy zamyka się modal, to on jest usuwany z DOM. Brakuje mi tego w teście.

2022-02-09 14:56 UTC, alexsimkovich commented on components/Modal/ModalPortalCreator.test.js
> +    expect(mockOnClick).toHaveBeenCalledTimes(1)
to samo tutaj

2022-02-09 14:56 UTC, alexsimkovich commented on components/Modal/ModalPortalCreator.test.js
> +    expect(mockOnClick).toHaveBeenCalledTimes(1)
tutaj też

2022-02-09 14:56 UTC, alexsimkovich commented on components/Modal/ModalPortalCreator.js
> +  ), root)
Ja bym tutaj zwracał tylko `ModalOverlay lub Backdrop`:
```
return createPortal((
    <>
      <ModalOverlay>{props.children}</ModalOverlay>
    </>
  ), root)
```

Dla mnie backdrop to jest to samo co overlay :) Czyli to co zajmuje całość i jest przejrzyste. Wybierz to lub to.
A to co będzie w środku - przeniósł by do konkretnego modala

2022-02-09 14:56 UTC, alexsimkovich commented on components/Modal/SetPasswordModal.js
> +}
z tego, co było w środku portala zrobiłbym generyczny modal komponent, który by miał biały kontener, przyciski z obsługą oraz przyjmował warunkowo Ikonkę.

2022-02-12 12:08 UTC, lukasz-galka requested changes

2022-02-12 12:08 UTC, lukasz-galka commented on components/Modal/ModalPortal.js
> +}
portal powinien byc odpowiedzialny jedynie za tworzenie portalu, a modal powinien byc odpwiedzialny za pokazywanie/chowanie itp mozesz zobaczyc ogolny przyklad tutaj https://blog.logrocket.com/build-modal-with-react-portals/ (u nas  to id portalu moze byc jak mamy teraz)

wiec modal powinien miec props isOpen i on powinien decydowac czy modal jest widoczny, a portal powinien byc caly czas w DOM

atrybuty powinny byc w modalu a nie na portalu, ale ustawmy aktualnie jedynie aria-hidden i role dialog, labelki mozemy chilowo pominac
```
 element.setAttribute('aria-hidden', 'false')
  element.setAttribute('aria-lebelledby', 'modalTitle')
  element.setAttribute('aria-describedby', 'modalSubtitle')
  element.setAttribute('role', 'dialog')
```

context nie jest Ci juz wtedy potrzebny,

2022-02-15 16:47 UTC, lukasz-galka requested changes

2022-02-15 16:47 UTC, lukasz-galka commented on components/Input/style.js
> +  @media (min-width: 576px) {
podstawowy input nie powinien miec szerokosci na sztywno, powinna ona byc ustawiana w komponentach ktore korzystaja z niego

2022-02-15 16:47 UTC, lukasz-galka commented on components/Modal/Modal.js
> +    const closeOnEscapeKey = e => e.key === 'Escape' ? handleClose() : null
nie bylo tego w wymaganiach, ale jak juz dodajesz to dodaj tez test pod ten przypadek

2022-02-15 16:47 UTC, lukasz-galka commented on components/Modal/Modal.js
> +    return () => {
czy potrzebujesz tutaj 2 useEffect, nie mozna obu przypadkow ograc za pomoca `isOpen` ?

2022-02-15 16:47 UTC, lukasz-galka commented on components/Modal/style.js
> +    width: 112px;
a co jak zmieni sie tekst? zmien tekst w buttonie i zobacz jak sie renderuje, wykorzystaj `width: auto`

2022-02-15 16:47 UTC, lukasz-galka commented on components/Modal/style.js
> +  display: flex;
jak zauwazylismy na demo, ikonka ma zły rozmiar

2022-02-15 16:47 UTC, lukasz-galka commented on components/Modal/Modal.test.js
> +    expect(mockOnClick).toHaveBeenCalledTimes(1)
daj nowa linie przed `expect`

2022-02-15 16:47 UTC, lukasz-galka commented on pages/index.page.js
> +    const mainPage = document.querySelector('.container')
po co te aria hidden tutaj? juz jest na modalu i tam wystarczy

2022-02-15 16:47 UTC, lukasz-galka commented on pages/index.test.js
> +  it('should open Modal after button click and close it after click on backdrop', () => {
dodaj moze tutaj TODO aby przeniesc te testy po integracji modala w tile

2022-02-15 16:47 UTC, lukasz-galka commented on components/ContextMenu/ContextMenu.js
> +  }, [isActive, changeStateHandler])
czemu tutaj te zmiany? jak sa potrzebne to dodaj je moze w tym drugim mr od context menu w tile

2022-02-15 16:47 UTC, lukasz-galka commented on components/Modal/style.js
> +  `
poformatuj style aby ` byl w odpowienim miejscu

2022-02-15 18:18 UTC, alexsimkovich requested changes

2022-02-15 18:18 UTC, alexsimkovich commented on components/ContextMenu/ContextMenu.js
> +  }, [isActive, changeStateHandler])
i dlaczego zmieniłeś to na `useCallback`?

2022-02-15 18:18 UTC, alexsimkovich commented on components/ReactPortal/ReactPortal.js
> +  if (wrapperElement === null) return null
`if (!wrapperElement) return null`

2022-02-18 17:35 UTC, karosmyr commented on pages/index.page.js
> +    const mainPage = document.querySelector('.container')
Napisałem Ci na slacku wiadomość co do tego, narazie zostawiam jak jest. Daj znać to najwyżej wrzuce szybko zmianę.

2022-02-19 09:06 UTC, lukasz-galka approved these changes

2022-02-19 17:04 UTC, alexsimkovich approved these changes

2022-02-28 15:09 UTC, merged