feat: P2022-260 Create board component
intive/patronage22_szczecin_js pull request #21
Opened 2022-01-30 18:47 UTC by Noshi96

2022-02-04 09:37 UTC, alexsimkovich requested changes

2022-02-04 09:37 UTC, alexsimkovich commented on components/NewBoardModal/NewBoardModal.js
> +const CreateNewBoardModal = (props) => {
This is a bad name of the component as well as the name of the file. Must be more meaningful (i.e `Board Wizard or Board Creator or Board Portal or BoardCreatorPortal)

2022-02-04 09:37 UTC, alexsimkovich commented on components/NewBoardModal/NewBoardModal.js
> +          <Title>{props.title}</Title>
This modal component itself should have only overlay, X icon and buttons. Other content should come as a `props.children`

2022-02-04 09:37 UTC, alexsimkovich commented on components/NewBoardModal/NewBoardModal.js
> +import ReactDOM from 'react-dom'
`import { createPortal } from 'react-dom'`

2022-02-04 09:37 UTC, alexsimkovich commented on components/NewBoardModal/NewBoardModal.js
> +  ), document.querySelector('body'))
`document.querySelector('body')` => `document.body`

2022-02-04 09:37 UTC, alexsimkovich commented on components/NewBoardModal/NewBoardModal.js
> +  ), document.querySelector('body'))
Sugestia:
1. Stwórz ogólną funkcje w tym pliku (np. addContainer), która będzie przyjmowała `id` i będzie tworzyła za pomocom JS-a diva z id-kiem, który podasz i robiła `document.body.append.
2. wtedy urzyj tej funkcji przy tworzeniu portała:
  `const root = addContainer('create-new-board')`
  i tego `root`-a dodasz przy tworzeniu portala (zamiast `document.querySelector('body')`)

2022-02-09 13:36 UTC, lukasz-galka requested changes

2022-02-09 13:36 UTC, lukasz-galka commented on components/BoardCreatorPortal/BoardCreatorPortal.js
> +
Troche zrobiles wiecej niz trzeba, mozesz zachowac sobie te zmiany co masz gdzies na boku, ale chwilowo chcialbym abysmy zrobili jedynie ta podstawowa wersje, co byla opisana w tikecie, czyli mamy zrobic jedynie pierwszy ekran

![image](https://user-images.githubusercontent.com/17024927/153210450-3262eeab-d4b6-4b79-9cb5-ab79f923c921.png)

wiec, zrobilbym tak,
1. nazwij ten komponent po prostu BoardCreator
2. komponent Board Creator powinien byc odpowiedzialny za ten caly modal, biale tło, tytuł "Create new Board", przycisk continue, ogarniac portal
3. Powinnismy miec drugi komponent BoardCreatorWizard, ktory bedzie odpowiedzialny za kolejne stepy tworzenia boardu, chwilowo mozemy zaczac prosto, i bedzie on mial tylko jeden step - labelka i input od nazwy boardu, potem bedziemy dodawac kolejne stepy

Czyli struktura w uproszczeniu wyglada tak

```
<BoardCreator>
  X
  Title
  <BoardCreatorWizard>
  Buttons
</BoardCreator>
```

2022-02-12 12:41 UTC, lukasz-galka requested changes

2022-02-12 12:41 UTC, lukasz-galka commented on components/BoardCreator/BoardCreator.js
> +            <Title>{props.children[0]}</Title>
ten komponent bedzie wykorzystywany jedynie do tworzenia boardow, wiec mozemy miec tutaj klucze na sztywno, nie musimy przyjmowac je przez propsy

2022-02-12 12:41 UTC, lukasz-galka commented on components/BoardCreator/BoardCreatorWizard.js
> +
po co rozbicie na 2 komponenty? wyrenderuj w tym komponencie, ten subtitle i input, po co ten `id` i `ref` ?

2022-02-12 12:41 UTC, lukasz-galka commented on components/BoardCreator/BoardCreatorWizard.js
> +      <TextInputInBoardCreatorWizard {...props} />
wyniesmy ten board creator wizard do glownego katalogu, aktualnie mamy wszystko w `components`

2022-02-12 12:41 UTC, lukasz-galka commented on components/BoardCreator/style.js
> +  padding-right: 2.8rem;
po co ten padding? mozesz ustalic pozycja za pomoca top/right ktore juz masz, i niech one beda mialy jakies normalne waetosci a nie 1.813

![image](https://user-images.githubusercontent.com/17024927/153711620-80b13d89-639a-42a3-95e4-930054fdd6fe.png)

2022-02-12 12:41 UTC, lukasz-galka commented on components/BoardCreator/style.js
> +  @media (max-width: 768px) {
piszemy style mobile first, wiec korzystaj z  min-width

2022-02-12 12:41 UTC, lukasz-galka commented on components/BoardCreator/style.js
> +    width: 40%;
czemu 40? moze zajac cala przestrzen jak jest jeden button

2022-02-12 12:41 UTC, lukasz-galka commented on components/BoardCreator/style.js
> +export const StyledIcon = styled(Icon)`
korzystasz gdzies z tego StyledIcon? wyczysc nie wykorzystane style

2022-02-12 12:41 UTC, lukasz-galka commented on components/ModalPortal/ModalPortal.js
> +import { useEffect } from 'react'
ogolnie, tutaj z portalem musimy poczekac na pr od Konrada, on doda juz ten komponent i wtedy go sobie wykorzystasz

2022-02-12 17:33 UTC, Noshi96 commented on components/ModalPortal/ModalPortal.js
> +import { useEffect } from 'react'
Na razie ten mój (on jest w sumie właśnie od Konrada) zostawiam i tak jak piszesz, gdy pojawi się już zatwierdzony u Konrada to poprawie

2022-02-12 17:44 UTC, Noshi96 commented on components/BoardCreator/style.js
> +  padding-right: 2.8rem;
Okej źle patrzyłem na figmie, już widzę gdzie to jest :D
![image](https://user-images.githubusercontent.com/38572172/153722119-840fe3c5-cb75-4937-824a-d9330a51a7e1.png)

2022-02-12 18:44 UTC, Noshi96 commented on components/BoardCreator/BoardCreatorWizard.js
> +
Jak nie dam id przy inpucie to nie wyświetlają się ostatnio wpisywane nazwy, pytanie czy chcemy żeby się to wyświetlało czy nie?
![image](https://user-images.githubusercontent.com/38572172/153723990-62926c76-a5e9-4c46-939a-aa835b8b7d40.png)

2022-02-12 18:45 UTC, Noshi96 commented on components/BoardCreator/BoardCreatorWizard.js
> +
Myślałem, że ref będzie spoko jakbyśmy chcieli wyciągać później wartość z inputa przy użyciu useRef(), usunąć to czy zostajemy przy tym?

2022-02-12 19:39 UTC, Noshi96 commented on components/BoardCreator/BoardCreatorWizard.js
> +
Jeśli chodzi o to dlaczego rozbiłem na 2 komponenty. Jak mamy wykorzystywać BoardWizard w next stepach to widziałem to w ten sposób:
```javascript
import { Subtitle, TextInput } from './style'
import { useTranslation } from 'next-i18next'

const BoardCreatorWizard = (props) => {
  return (
    props.withTextInput
      ? <TextInputInBoardCreatorWizard {...props} />
      : props.withVoteList
        ? <VoteListInBoardCreatorWizard />
        : props.withTemplates
          ? <TemplatesBoardCreatorWizard />
          : null
  )
}

const TextInputInBoardCreatorWizard = (props) => {
  const { t } = useTranslation('common')
  return (
    <>
      <Subtitle>{t('createNewBoard.createNewBoardSubtitle')}</Subtitle>
      <TextInput id='boardname' type='text' ref={props.boardNameRef} />
    </>
  )
}

const VoteListInBoardCreatorWizard = (props) => {

}

const TemplatesBoardCreatorWizard = (props) => {

}

export default BoardCreatorWizard
```

Czy to złe podejście? 

Czy zrobić po prostu tak:
```javascript
import { Subtitle, TextInput } from './style'
import { useTranslation } from 'next-i18next'

const BoardCreatorWizard = (props) => {
  const { t } = useTranslation('common')
  return (
    <>
      <Subtitle>{t('createNewBoard.createNewBoardSubtitle')}</Subtitle>
      <TextInput id='boardname' type='text' ref={props.boardNameRef} />
    </>
  )
}

export default BoardCreatorWizard
```

2022-03-03 07:08 UTC, lukasz-galka requested changes

2022-03-03 07:08 UTC, lukasz-galka commented on components/BoardCreatorWizard/BoardCreatorWizard.test.js
> +    const modal = render(
wyciagaj od razu potrzebne elementy https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-wrapper-as-the-variable-name-for-the-return-value-from-render

2022-03-03 07:08 UTC, lukasz-galka commented on components/BoardCreatorWizard/BoardCreatorWizard.js
> +      <TextInput id='boardname' type='text' ref={props.boardNameRef} />
skasujmy chwilowo ten id i ref

2022-03-03 07:08 UTC, lukasz-galka commented on components/BoardCreator/style.js
> +
czy testowales to na telefonie gdy otworzy sie klawiatura?

2022-03-03 07:08 UTC, lukasz-galka commented on components/BoardCreator/BoardCreator.js
> +          <BoardCreatorWizard {...props} />
chwiloeo nie potrzebujemy przekazywac propsow to wizarda

2022-03-03 14:22 UTC, Noshi96 commented on components/BoardCreator/style.js
> +
Tak, wygląda to tak:
![image](https://user-images.githubusercontent.com/38572172/156583317-9f27d017-0e2a-417d-ba96-715ee3ce0b47.png)


![image](https://user-images.githubusercontent.com/38572172/156583229-adca6daf-dbc4-441b-b237-7eb30088396f.png)

2022-03-04 14:05 UTC, lukasz-galka requested changes

2022-03-04 14:05 UTC, lukasz-galka commented on components/BoardCreatorWizard/style.js
> +  &:focus {
nie mozna kasowac focus outline, jest on bardzo wazny dla accessibility

2022-03-04 14:05 UTC, lukasz-galka commented on components/BoardCreatorWizard/style.js
> +  &:-webkit-autofill {
potrzebujemy to `-webkit-autofill` ?  nie uzywamy `!important`

2022-03-04 14:05 UTC, lukasz-galka commented on components/BoardCreatorWizard/BoardCreatorWizard.test.js
> +    const { container: boardCreatorWizard } = render(
nie musisz zmieniac tych nazw, po prostu w testach korzystaj `container` tak samo w inncyh testach

2022-03-04 16:25 UTC, Noshi96 commented on components/BoardCreatorWizard/style.js
> +  &:-webkit-autofill {
To było mi potrzebne jak wyświetlały się ostatnio wpisywane nazwy w inpucie, ale teraz faktycznie nie jest to potrzebne

2022-03-04 16:37 UTC, Noshi96 commented on components/BoardCreatorWizard/style.js
> +  &:focus {
![image](https://user-images.githubusercontent.com/38572172/156802761-0193ede0-913c-4a39-84a5-2c464ed05fac.png)
Okej, to dla pewności dopytam czy chcemy żeby tak wyglądało jak wyżej gdy mamy focus i wpisujemy nazwę?

2022-03-05 14:40 UTC, lukasz-galka approved these changes

2022-03-06 17:13 UTC, alexsimkovich approved these changes

2022-03-08 16:57 UTC, merged