WIP: feat: P2022-548 Render word card or cards
intive/patronage22_szczecin_js pull request #23
Opened 2022-02-02 12:41 UTC by karosmyr

2022-02-04 10:26 UTC, lukasz-galka requested changes

2022-02-04 10:26 UTC, lukasz-galka commented on components/BoardTile/BoardTile.test.js
> +
sugerowalbym to przeniesc do `jest.setup.js` i mokowac `next-i18next` dzieki temu zniknie ten warning dla wszystkich testow

2022-02-04 10:26 UTC, lukasz-galka commented on components/BoardTile/BoardTile.test.js
> +
neistety nie mamy dostepu do wartosci translacji, jedynie do kluczy, wiec nie przetestujemy tego za pomoca naszych unitowych, bedzie to musialo byc sprawdzane w e2e

2022-02-04 10:26 UTC, lukasz-galka commented on components/Header/style.js
> +  z-index: 10;
a te zmiany nie za z `main`?

2022-02-04 11:40 UTC, karosmyr commented on components/BoardTile/BoardTile.test.js
> +
Zadziałało

2022-02-04 11:40 UTC, karosmyr commented on components/Header/style.js
> +  z-index: 10;
Tak z main, juz jest rebase zrobiony wiec wszystko się zgadza.

2022-02-04 11:51 UTC, lukasz-galka approved these changes

2022-02-04 11:53 UTC, alexsimkovich approved these changes

2022-02-07 16:22 UTC, WDaniszewska commented
Tested on feat/P2022-548/render-word-card-or-cards branch,
browser: Google Chrome version 97.0.4692.99,
system: Windows 10
result: passed

2022-02-08 06:39 UTC, merged