feat: P2022-04 Add board list
intive/patronage22_szczecin_js pull request #25
Opened 2022-02-09 12:11 UTC by grumpyjacek

Breakpointy utworzyłem na podstawie P2022-922.

2022-02-09 14:09 UTC, alexsimkovich requested changes

2022-02-09 14:09 UTC, alexsimkovich commented on components/BoardList/style.js
> +    //justify-content: center;
remove or uncomment if necessary ?!

2022-02-09 14:21 UTC, lukasz-galka requested changes

2022-02-09 14:21 UTC, lukasz-galka commented on components/BoardList/style.js
> +    //justify-content: center;
poczysc zakomentowane style

2022-02-09 14:21 UTC, lukasz-galka commented on pages/index.page.js
> +export async function getServerSideProps (ctx) {
jak mozesz to poczysc juz buttony z homa, mamy je wykorzystane w innych komponentach, wiec juz ich tutaj nie potrzebujemy

2022-02-10 11:29 UTC, grumpyjacek commented on components/BoardList/style.js
> +    //justify-content: center;
Forgot about it :(

2022-02-10 11:30 UTC, grumpyjacek commented on pages/index.page.js
> +      cardCount: board.columns ? Object.keys(board.columns).length : 0
Pomroczność jasna mnie dopadła ;)

2022-02-10 11:30 UTC, grumpyjacek commented on pages/index.page.js
> +    const res = await axios.get('http://localhost:3000/api/boards')
Użyta

2022-02-10 11:31 UTC, grumpyjacek commented on pages/index.page.js
> +export async function getServerSideProps (ctx) {
Wyrzucone

2022-02-10 11:31 UTC, grumpyjacek commented on components/BoardList/style.js
> +    //justify-content: center;
Przegapiłem wcześniej :(

2022-02-10 11:31 UTC, grumpyjacek commented on pages/index.page.js
> +    const boardList = data.map(board => ({
Zrobione (chyba) :)

2022-02-10 11:32 UTC, grumpyjacek commented on components/BoardList/BoardList.js
> +export default function BoardList ({ boardList }) {
Done :)

2022-02-10 14:03 UTC, lukasz-galka requested changes

2022-02-11 12:29 UTC, grumpyjacek commented on components/BoardTilesList/BoardTilesList.test.js
> +    expect(list.getByText('mockedName')).toBeInTheDocument()
Jasne, zrobione (mam nadzieję :) ).

2022-02-11 12:32 UTC, grumpyjacek commented on services/internal-api/index.js
> +
Zrobiłem. Chyba :) Ale testów jeszcze nie ma, będę w weekend walczył z nimi.

2022-02-11 12:32 UTC, grumpyjacek commented on pages/index.page.js
> +      notFound: true
Wyrzucone

2022-02-15 10:17 UTC, grumpyjacek commented on services/internal-api/index.js
> +
Zamknę tę część, bo jest zrobione, tylko ostatni test pozostał T_T

2022-02-15 10:34 UTC, alexsimkovich requested changes

2022-02-15 10:34 UTC, alexsimkovich commented on pages/api/boards/index.page.js
> +    res.statusCode = 500
powinnismy zwracać 400

2022-02-15 10:34 UTC, alexsimkovich commented on services/internal-api/index.js
> +  return axiosInstance.get('http://localhost:3000/api/boards', { params: Object.assign({}, ...args) })
nie jest potrzebny host tutaj

2022-02-15 11:47 UTC, grumpyjacek commented on pages/api/boards/index.page.js
> +    res.statusCode = 500
Zrobione.

2022-02-16 14:08 UTC, alexsimkovich approved these changes

2022-02-16 16:44 UTC, lukasz-galka requested changes

2022-02-16 16:44 UTC, lukasz-galka commented on pages/api/boards/getBoards.js
> +export default async function getBoards (req, res, database, dbPrefix) {
powinienes wyeksportowac jedynie `getBoards`, getLocalDate i getCardCount to powinny byc metody prywatne

2022-02-16 16:44 UTC, lukasz-galka commented on pages/api/boards/getBoards.test.js
> +describe('getCardCount', () => {
tak jak pisalem wyzej, to sa metody prywatne, testujemy jedynie `getBoards` i tam powinienes poprzez odpowiedni model przetestowac te przypadki

2022-02-16 16:44 UTC, lukasz-galka commented on pages/api/boards/getBoards.test.js
> +  it('should map a board without a password', async () => {
should return board...

2022-02-16 16:44 UTC, lukasz-galka commented on pages/api/boards/getBoards.test.js
> +
dodaj test gdzie sa 2 boardy

2022-02-16 16:44 UTC, lukasz-galka commented on pages/index.page.js
> +export default function Home ({ tilesList }) {
jest jakis problem z preview u Ciebie, pojawia sie 500, sprawdze potem

2022-02-16 21:21 UTC, grumpyjacek commented on pages/api/boards/getBoards.test.js
> +describe('getCardCount', () => {
Hej, czytałem, że nie powinno się generalnie wystawiać na zewnątrz prywatnych metod, ale nie wiem, jak inaczej je złapać do testu, bo test ich nie widział. Czy poprzez utworzenie "odpowiedniego modelu" masz na myśli odtworzenie tych metod w samym teście?

2022-02-17 06:28 UTC, lukasz-galka commented on pages/api/boards/getBoards.test.js
> +describe('getCardCount', () => {
powinienes przetestowac jedynie metody publiczne, czyli jedynie `getBoards` i tylko ona Cie interesuje, co sie dzieje w srodku to juz inne sprawa, i to co sie dzieje w srodku moze sie zmieniac dowolne, ale rezultat powinien byc taki sam. 

tak, ustawianie daty, czyli ta funkcja `getLocalDate` jest juz przetestowana, brakuje sprawdzania czy ilosc kartek jest zliczna poprawnie, wiec jak mokujesz odpowiedz

```
    snapshot.val.mockReturnValue({
      111: {
        name: 'board 1',
        createdAt: '1984-10-16T12:30:00.000Z'
      }
    })
```

to poprostu tutaj musz dodac `columns` abyt Twoj kod mogl je znalezc i zliczyc, bo aktualnie zawsze masz `0`

2022-02-17 09:48 UTC, grumpyjacek commented on pages/api/boards/getBoards.js
> +export default async function getBoards (req, res, database, dbPrefix) {
Zawrócone na prywatne.

2022-02-17 09:50 UTC, grumpyjacek commented on pages/api/boards/getBoards.test.js
> +describe('getCardCount', () => {
Dziękuję! Jeszcze wiele do nauczenia się... :)

2022-02-17 09:50 UTC, grumpyjacek commented on pages/api/boards/getBoards.test.js
> +
Dodane.

2022-02-17 10:48 UTC, alexsimkovich requested changes

2022-02-17 10:48 UTC, alexsimkovich commented on pages/api/boards/getBoards.test.js
> +    expect(res.json).toHaveBeenCalledWith([{
Use `.toHaveBeenCalledWith` to ensure that a mock function was called with specific arguments.
Ty chyba spodziewasz się że wartość w odpowiedzi będzie taka, a nie to że funkcja została wywołana z takimi argumentami.   

2022-02-17 10:48 UTC, alexsimkovich commented on pages/api/boards/getBoards.test.js
> +    expect(res.json).toHaveBeenCalledWith([
same here

2022-02-17 10:48 UTC, alexsimkovich commented on pages/api/boards/index.test.js
> +    expect(getBoards).toHaveBeenCalledWith(req, res, database, 'prefix')
a tutaj poprawnie użyłeś :)

2022-02-18 09:31 UTC, grumpyjacek commented on pages/api/boards/getBoards.test.js
> +    expect(res.json).toHaveBeenCalledWith([{
This solution was proposed by Łukasz.

2022-02-18 09:31 UTC, grumpyjacek commented on pages/api/boards/getBoards.test.js
> +    expect(res.json).toHaveBeenCalledWith([
Here as well :)

2022-02-18 14:18 UTC, lukasz-galka requested changes

2022-02-18 14:18 UTC, lukasz-galka commented on pages/api/boards/getBoards.test.js
> +  it('should return a board with five cards', async () => {
five?

2022-02-18 14:18 UTC, lukasz-galka commented on services/internal-api/index.js
> +  baseURL: `https://${process.env.NEXT_PUBLIC_VERCEL_URL}` || 'http://localhost:3000',
wrzucilem na to na `main` wiec mozesz zrobic rebase

2022-02-19 08:33 UTC, lukasz-galka commented on pages/api/boards/getBoards.test.js
> +    expect(res.json).toHaveBeenCalledWith([{
Jacek, zrobmy jeszcze jedna poprawke, wrzucmy jednak zawartosc getBoards do index

```
import { dbConnect, dbPrefix } from '../../../libs/dbClient'
import { ref, child, get } from 'firebase/database'

const handlers = {
  get: getBoards
}

export default async function handler (req, res) {
  let database

  try {
    database = await dbConnect()
  } catch (err) {
    console.error(err)
    res.statusCode = 400
    res.end()
  }

  const { method } = req
  const handler = handlers[method.toLowerCase()]

  if (handler) return handler(req, res, database, dbPrefix)
  else {
    res.setHeader('Allow', ['GET'])
    res.status(405)
    res.end(`Method ${method} Not Allowed`)
  }
}

async function getBoards (req, res, database, dbPrefix) {
  const snapshot = await get(child(ref(database), `${dbPrefix}/boards`))
  if (!snapshot.exists()) return []

  const snapshotValue = snapshot.val()
  const data = Object.keys(snapshot.val()).map(key => ({
    ...snapshotValue[key],
    id: key
  }))

  const getLocalDate = (date) => {
    const createdDate = new Date(date)
    const options = { day: 'numeric', month: 'short', year: 'numeric' }
    return createdDate.toLocaleDateString('en', options)
  }

  const getCardCount = (columns) => {
    if (!columns) {
      return 0
    } else {
      return Object.keys(columns).reduce((acc, key) => {
        acc = acc + Object.keys(columns[key].cards).length
        return acc
      }, 0)
    }
  }

  const tilesList = data.map(board => ({
    id: board.id,
    name: board.name,
    hasPassword: !!board.hasPassword,
    createdAt: getLocalDate(board.createdAt),
    cardCount: getCardCount(board.columns)
  }))

  res.json(tilesList)
}
```

a w testach wykorzystajmy https://www.npmjs.com/package/node-mocks-http

ponizej testy w index.page.js, i jeden test w sekcji `api/boards get` - przenies tam reszte swoich testow

```

/* globals describe, it, expect, jest  */

import { createMocks } from 'node-mocks-http'
import { get } from 'firebase/database'
import handler from './index.page'

const database = {}

jest.mock('firebase/database')
jest.mock('../../../libs/dbClient', () => ({
  dbConnect: jest.fn().mockImplementation(() => database),
  dbPrefix: 'prefix'
}))

const snapshot = {
  exists: jest.fn(),
  val: jest.fn()
}

get.mockResolvedValue(snapshot)

describe('api/boards', () => {
  it('should return 405 if the method is not allowed', async () => {
    const { req, res } = createMocks({
      method: 'DELETE',
      url: '/api/boards'
    })

    await handler(req, res)

    expect(res._getStatusCode()).toEqual(405)
    expect(res._getHeaders()).toEqual({ allow: ['GET'] })
  })

  describe('api/boards get', () => {
    it('should return a board without a password', async () => {
      snapshot.exists.mockReturnValue(true)

      snapshot.val.mockReturnValue({
        111: {
          name: 'board 1',
          createdAt: '1984-10-16T12:30:00.000Z'
        }
      })

      const { req, res } = createMocks({
        method: 'GET',
        url: '/api/boards'
      })

      await handler(req, res)

      expect(res._getStatusCode()).toEqual(200)
      expect(res._getJSONData()).toEqual([{
        id: '111',
        name: 'board 1',
        cardCount: 0,
        hasPassword: false,
        createdAt: 'Oct 16, 1984'
      }])
    })
  })
})
```

2022-02-20 14:14 UTC, lukasz-galka commented on pages/api/boards/index.test.js
> +    snapshot.exists.mockReturnValue(false)
pusta tablice tez powiniesmy zwrocic jako jsona, return res.json([])

2022-02-20 15:59 UTC, lukasz-galka approved these changes

2022-02-21 07:55 UTC, alexsimkovich approved these changes

2022-02-21 07:55 UTC, alexsimkovich commented on package.json
> +    "node-mocks-http": "^1.11.0",
usuń proszę `^`

2022-02-21 08:19 UTC, grumpyjacek commented on package.json
> +    "node-mocks-http": "^1.11.0",
usunięte

2022-02-25 08:23 UTC, merged