feat: P2022-68 Integrate ContextMenu into BoardTile
intive/patronage22_szczecin_js pull request #27
Opened 2022-02-13 23:58 UTC by karosmyr

2022-02-15 18:11 UTC, alexsimkovich requested changes

2022-02-15 18:11 UTC, alexsimkovich commented on components/ContextMenu/ContextMenu.js
> +  }, [isActive])
Dlaczego użyłeś tutaj `useCallback`?

2022-02-16 14:07 UTC, alexsimkovich commented on components/BoardTile/BoardTile.js
>  }
zostawmy to jak jest, jak coś, to później zrobimy refactor

2022-02-19 09:41 UTC, lukasz-galka requested changes

2022-02-19 09:41 UTC, lukasz-galka commented on components/BoardTile/BoardTile.js
> +        <ContextMenu id='5'>
baord tile powinien dostac id jako props, i tutaj mozesz je wykorzsyac

2022-02-19 09:41 UTC, lukasz-galka commented on components/ContextMenu/style.js
> +  line-height: 0.5;
daj mu display flex zamiast tego line-height

2022-02-19 09:41 UTC, lukasz-galka commented on components/ContextMenu/style.js
> +  right: 0;
potrzebujesz top i margin-top? wykorzystaj jedno

2022-02-19 09:41 UTC, lukasz-galka commented on components/BoardTile/BoardTile.js
> +// import { Date, Header, IconWrapper, Text, Tile } from './style'
wyczysc komentarze

2022-02-19 17:02 UTC, alexsimkovich approved these changes

2022-02-21 17:33 UTC, lukasz-galka approved these changes

2022-02-22 06:18 UTC, merged