feat: P2022-261 Render board details page
intive/patronage22_szczecin_js pull request #28
Opened 2022-02-14 15:06 UTC by AnnaSawickaZiolkowska

https://tracker.intive.com/jira/browse/P2022-261
https://patronage22-szczecin-js-bcbq5oa6l-patronage22szczecinjs.vercel.app/

2022-02-19 16:56 UTC, alexsimkovich requested changes

2022-02-19 16:56 UTC, alexsimkovich commented on components/BoardHeader/style.js
> +`
popraw formatowanie kodu wyżej

2022-02-19 16:57 UTC, alexsimkovich commented
@AnnaSawickaZiolkowska masz dużo zakomentowanego kodu. Jak Ci coś nie działa - dawaj pomożemy Ci naprawić

2022-02-19 17:23 UTC, AnnaSawickaZiolkowska commented
> 

tak wiem,.. generalnie ten kod działał zanim zrobiłam rebase z main i szczerze jeszcze nie czuję się na siłach, żeby to dzisiaj ogarnąć. Jutro będę nad tym siedzieć i będę pytać w razie wątpliwości. Teraz mi będzie łatwiej bo już wiecie co w kodzie jest :)
Strony boards z tego co mówił Łukasz to i tak nie będzie.

2022-02-23 18:01 UTC, lukasz-galka requested changes

2022-02-23 18:01 UTC, lukasz-galka commented on pages/boards/[id].page.js
> +  const board = resData.data.find(board => board.id === boardId)
ogolnie tutaj powinnisy miec `getBoard`, ale nie wiem juz jak umawialismy sie w tikecie... wiec jak cos to mozesz zostawic tak jak jest, najwyzej zrobimy dodatkowy tiket na przepiecie sie na nowe api od detali

2022-02-24 21:48 UTC, AnnaSawickaZiolkowska commented on pages/boards/[id].page.js
> +  const board = resData.data.find(board => board.id === boardId)
z tego co pamiętam to tego nie ustalaliśmy... jak wycenialiśmy ten tiket to dane nie miały być z db, chyba się to w trakcie zmieniło
teraz jest tylko informacja - data from DB is used

2022-02-25 18:03 UTC, lukasz-galka commented on pages/boards/[id].page.js
> +  const board = resData.data.find(board => board.id === boardId)
to zostawmy jak jest

2022-02-28 17:55 UTC, lukasz-galka requested changes

2022-03-03 07:34 UTC, lukasz-galka requested changes

2022-03-03 07:34 UTC, lukasz-galka commented on components/BoardTile/style.js
> +  box-sizing: border-box;
po co te zmiany od tile? docelowo caly tile bedzie klikalny, a nie tylko header

2022-03-03 07:34 UTC, lukasz-galka commented on pages/boards/[id]/index.page.js
> +      tilesList: board,
czemu `tilesList` ? masz w tej zmiennej liste czy moze jeden element?

2022-03-03 07:34 UTC, lukasz-galka commented on pages/boards/[id]/index.page.js
> +        <h2 style={{ fontWeight: 'normal', marginTop: '20px' }}>board details page {tilesList.id}</h2>
skasuj to h2, ktory board jest otwarty widzimy przez nazwe

2022-03-03 07:34 UTC, lukasz-galka commented on pages/boards/[id]/index.page.test.js
> +  const tilesList = {
tutaj tez zmien to `tilesList`

2022-03-03 07:34 UTC, lukasz-galka commented on pages/boards/[id]/index.page.test.js
> +  it('should render Header', () => {
powinien wyrenderowac jedynie Header?

2022-03-03 07:34 UTC, lukasz-galka commented on pages/index.page.js
> +            <h4 style={{ cursor: 'pointer' }}>{board.name}</h4>
czemu `h4` a nie `a`?

2022-03-03 07:34 UTC, lukasz-galka commented on pages/boards/[id]/index.page.js
> +        {props.children}
po co to props children?

2022-03-03 07:34 UTC, lukasz-galka commented on pages/boards/[id]/index.page.js
> +
zrob tez rebase bo sa jakies konflikty

2022-03-03 07:34 UTC, lukasz-galka commented on pages/boards/[id]/index.page.js
> +      <Header title={t('headerTitle')} />
powinnismy tutaj tez skorzystac z layoutu, pewnie mialas problem z marginesami i board hederem, wiec zrobmy tak
- skasuj ten padding z `main` i ustaw go na boards list, dzieki temu bedziesz mogla wrzucic normalnie board header w layout, board column mozesz zostawic chwilowo jedynie na home page

2022-03-04 09:32 UTC, AnnaSawickaZiolkowska commented on components/BoardTile/style.js
> +  box-sizing: border-box;
już cofnęłam zmiany, zapomniałam o tym pliku, że też zmieniłam

2022-03-04 09:46 UTC, AnnaSawickaZiolkowska commented on pages/boards/[id]/index.page.js
> +      tilesList: board,
bardzo ważna uwaga :) żeby mocno zwracać uwagę na nazewnictwo, aby było adekwatne do tego co faktycznie jest w zmiennych
zmieniłam na `tileDetails`

2022-03-06 07:46 UTC, AnnaSawickaZiolkowska commented on pages/boards/[id]/index.page.js
> +      <Header title={t('headerTitle')} />
Właśnie z tym Layoutem miałam największą zagwostkę. Ten `Wrapper` zaimportowałam z Layoutu, żeby w razie jakichś zmian, można to zrobić w jednym miejscu. 
Zrobiłam tak jak napisałeś. Jak usunęłam paddingi z `main` to `Wrapper` w ,Layout` też przestał być potrzebny, bo w sumie były w nim tylko paddingi, więc go usunęłam, żeby nie przeszkadzał.

2022-03-08 14:10 UTC, lukasz-galka requested changes

2022-03-08 14:10 UTC, lukasz-galka commented on components/BoardHeader/style.js
> +  padding: 0 -5%;
juz masz padding ustawiony wyzej

2022-03-08 14:31 UTC, alexsimkovich requested changes

2022-03-08 14:31 UTC, alexsimkovich commented on pages/index.page.js
> +              <h4 style={{ width: '100%', height: '1rem', marginTop: '0.5rem' }}>{board.name}</h4>
nie używaj inlajnowych styli

2022-03-10 16:33 UTC, lukasz-galka requested changes

2022-03-10 16:33 UTC, lukasz-galka commented on components/BoardTilesList/style.js
> +    padding: 0 2.5rem;
cos jest nie tak ze stylami, bo na XL pokazuja sie aktualnie 3 tile w rzedzie, wczesniej bylo 4

2022-03-12 08:47 UTC, lukasz-galka approved these changes

2022-03-13 08:46 UTC, merged