feat: P2022-927 Create toast component
intive/patronage22_szczecin_js pull request #29
Opened 2022-02-14 15:06 UTC by Noshi96

2022-02-19 09:54 UTC, lukasz-galka requested changes

2022-02-19 09:54 UTC, lukasz-galka commented on components/Toast/style.js
> +  right: 2rem;
caly toast powinien miec kolor zielony lub czerowny, a tekst i ikonka kolor bialy

2022-02-19 09:54 UTC, lukasz-galka commented on components/Toast/style.js
> +  border: none;
po co border none?

2022-02-19 09:54 UTC, lukasz-galka commented on components/Toast/style.js
> +  max-width:20rem;
po co max width? powinien miec taka szrokosc jak zawartosc

2022-02-19 09:54 UTC, lukasz-galka commented on components/ToastPortal/ToastPortal.js
> +import { useToastPortal } from './hooks/useToastPortal'
z tymi portalami poczekajmy jak zmergujemy od Konrada, powinno byc niedlugo

2022-02-19 17:01 UTC, Noshi96 commented on components/Toast/style.js
> +  max-width:20rem;
Zrobiłem to z myślą o mobilkach gdy wiadomość w toast jest długa:
Toast z max-wdith: 20rem;
![Zrzut ekranu 2022-02-19 174129](https://user-images.githubusercontent.com/38572172/154810282-103e0325-61a3-453f-8e04-737c713cb7b0.png)


I toast bez max-width
![Zrzut ekranu 2022-02-19 174253](https://user-images.githubusercontent.com/38572172/154810304-4989ef03-73da-42b0-8cd8-c0ea36d7e20b.png)


Myślę, że zostawię tam ten max-width: 20rem; i na większej rozdzielczości będzie @media:
```css
  @media (min-width: 768px) {
    max-width: 100%;
  }
```
Wtedy na mobilce będzie jak na screenie pierwszym, a na desktopie tak:
![Zrzut ekranu 2022-02-19 175724](https://user-images.githubusercontent.com/38572172/154810726-09811fef-ebeb-4e62-8504-8e08307d6a96.png)


Jak uważasz, tak git będzie?

2022-03-10 17:04 UTC, lukasz-galka requested changes

2022-03-10 17:04 UTC, lukasz-galka commented on components/ReactPortal/ReactPortal.js
> +    if (autoClose && systemCreated && element.parentNode) {
moglbys sprobowac zrobic bez zmian w tym pliku, tylko przekazac `isOpen` to toasta, i nim ustawic setTimeout aby go schowac?

2022-03-10 17:40 UTC, Noshi96 commented on components/Toast/helpers.js
> +export const uuid = () => {
Faktycznie już widzę :D

2022-03-10 17:43 UTC, Noshi96 commented on components/Toast/Toast.test.js
> +  it('should find Toast after button click, and delete it after 4sec', async () => {
Spoko

2022-03-10 18:28 UTC, Noshi96 commented on components/ReactPortal/ReactPortal.js
> +    if (autoClose && systemCreated && element.parentNode) {
Okej, poprawione

2022-03-12 09:04 UTC, lukasz-galka commented on components/Toast/Toast.test.js
> +})
potrzebujemy jeszcze testu na auto close, poszukaj jakis `fake timers`

2022-03-12 13:56 UTC, Noshi96 commented on components/Toast/Toast.test.js
> +})
Okej, dodany :D

2022-03-12 15:49 UTC, lukasz-galka approved these changes

2022-03-14 07:36 UTC, alexsimkovich approved these changes

2022-03-14 20:23 UTC, merged