feat: P2022-148 add Material Icons
intive/patronage22_szczecin_js pull request #3
Opened 2022-01-18 14:05 UTC by AnnaSawickaZiolkowska

Now we can use Material Icons

2022-01-19 12:19 UTC, alexsimkovich requested changes

2022-01-19 12:19 UTC, alexsimkovich commented on package.json
> +    "material-design-icons": "^3.0.1",
Please remove the caret `^`. Use explicit version.
More info here https://github.com/npm/node-semver#caret-ranges-123-025-004

2022-01-19 12:19 UTC, alexsimkovich commented on pages/index.page.js
> +import Head from "next/head";
Please install the `standard js` extention to your IDE. We would like all of you to write a code in one style.

2022-01-19 12:21 UTC, alexsimkovich commented
@AnnaSawickaZiolkowska please adjust the snapshot test.

2022-01-19 17:39 UTC, lukasz-galka commented on pages/index.page.js
> +import Head from 'next/head';
padaja Ci testy i dlatego nie przechodzi deploy, musisz zaaktualizowac snapshot, mozesz wykorzystac
```
npm run test -- --updateSnapshot
```

lub skrot ktory mamy w package.json
```
npm run jest:update
```

2022-01-19 17:42 UTC, lukasz-galka commented on package.json
> +    "material-design-icons": "3.0.1",
po co instalujesz paczke npm, skoro i tak wrzucasz font przez http?

2022-01-19 18:19 UTC, lukasz-galka commented on pages/index.page.js
> +            Material Icons <span className="material-icons">tag_faces</span>
moglabys zrobic od razu prosty komponent `Icon` ktory przyjmuje `name` jako nazwe ikonki?

2022-01-19 18:19 UTC, lukasz-galka commented on pages/index.page.js
> +        </div>
zrob prosze rebase z masterem i squash na commitach aby byl 1

2022-01-19 18:56 UTC, lukasz-galka commented on pages/index.page.js
> +        <link rel="icon" href="/favicon.ico" />
odnosnie nazwy commita https://cbea.ms/git-commit/#capitalize

2022-01-20 12:58 UTC, AnnaSawickaZiolkowska commented on pages/index.page.js
> +import Head from 'next/head';
zrobione

2022-01-20 12:58 UTC, AnnaSawickaZiolkowska commented on package.json
> +    "material-design-icons": "3.0.1",
poprawione

2022-01-20 13:00 UTC, AnnaSawickaZiolkowska commented on pages/index.page.js
> +            Material Icons <span className="material-icons">tag_faces</span>
komponent zrobiony, poza `name` dodałam również w propsach `styleClass` gdyby była potrzeba dodać do stylowania nazwę klasy.

2022-01-20 16:23 UTC, closed without merging