WIP feat: P2022-926 Update Board API
intive/patronage22_szczecin_js pull request #30
Opened 2022-02-15 21:51 UTC by MarcinSoltysik

2022-02-18 18:17 UTC, alexsimkovich requested changes

2022-02-18 18:17 UTC, alexsimkovich commented on pages/api/boards/patchBoard.js
> +import { ref, child, update } from 'firebase/database'
Spróbuj to przenieść do pliku `/boards/[id]/index.page.js` i połączyć z kodem. Wiem że Jacek zrobił to inaczej, ale spróbuj

2022-02-18 18:17 UTC, alexsimkovich commented on pages/api/boards/[id].page.js
> +import { dbConnect, dbPrefix } from '../../../libs/dbClient'
`/api/boards/[id].page.js` zmień na `/api/boards/[id]/index.page.js`

2022-02-19 08:16 UTC, lukasz-galka commented on pages/api/boards/schemas/patchBoard.schema.js
> +export const patchBoardSchema = {
moze zostawmy w osobnym pliku ale w katalogu wyzej, mozemy miec katalog `schema` w roocie i tam trzymac wszystkie schemy?

2022-02-20 10:45 UTC, MarcinSoltysik commented on pages/api/boards/schemas/patchBoard.schema.js
> +export const patchBoardSchema = {
głosowanie ? ;)

2022-02-20 19:16 UTC, MarcinSoltysik commented on pages/api/boards/schemas/patchBoard.schema.js
> +    password: {
Niby nie jest required, ale w sumie to chyba na tą chwilę jedyna rzecz jaką patch zmienia  i dałem, ale jak coś można usunąć required,  ale w tedy to chyba będzie pustego patcha puszczać.

2022-02-22 23:55 UTC, MarcinSoltysik commented on pages/api/boards/patchBoard.js
> +import { ref, child, update } from 'firebase/database'
@alexsimkovich nie bardzo rozumiem co mam z tym zrobić ?

2022-02-23 05:31 UTC, lukasz-galka requested changes

2022-02-23 05:31 UTC, lukasz-galka commented on pages/api/boards/patchBoard.js
> +import { ref, child, update } from 'firebase/database'
@MarcinSoltysik nie tworz oliku `patchBoard` tylko trzymaj wszystko w index.page.js, tak jak to jest u Jacka juz teraz

2022-02-28 06:15 UTC, lukasz-galka commented on pages/api/boards/[id]/index.test.js
> +    it('for ID', async () => {
abys dodal "missing"

2022-02-28 14:42 UTC, lukasz-galka requested changes

2022-02-28 14:42 UTC, lukasz-galka commented on package.json
> +    "node-mocks-http": "1.11.0",
node-mocks-http? robiles rebase z main?

2022-02-28 14:42 UTC, lukasz-galka commented on pages/api/boards/[id]/index.test.js
> +  describe('should return validation error for id', () => {
nie mozesz miec `id` w describe, bo potem nie pasuje do innych testow, dan w describe `should return validation error for` a potem reszta w `it`, przykladowo w tym piersszym `missing id`

2022-02-28 14:42 UTC, lukasz-galka commented on pages/api/boards/[id]/index.page.js
> +    res.statusCode = 400
mozesz miec po prosty `res.status(400).json(...)`

2022-03-01 17:57 UTC, alexsimkovich commented on pages/api/boards/[id]/__snapshots__/index.test.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
ten test w ogóle nie jest potrzebny.

2022-03-01 18:11 UTC, alexsimkovich requested changes

2022-03-01 18:11 UTC, alexsimkovich commented on pages/api/boards/[id]/index.page.js
> +    res.json()
`res.status(204)`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH#response

2022-03-01 18:11 UTC, alexsimkovich commented on pages/api/boards/[id]/index.test.js
> +  describe('should return empty 200 repsonse for', () => {
`should return status code 204`

2022-03-02 21:51 UTC, MarcinSoltysik commented on pages/api/boards/[id]/__snapshots__/index.test.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
@alexsimkovich ale który test ?

2022-03-03 06:36 UTC, lukasz-galka commented on config/breakpoints.js
> +const size = {
czemu te zmiany z mastera?

2022-03-03 06:41 UTC, lukasz-galka requested changes

2022-03-03 06:41 UTC, lukasz-galka commented on schema/patchBoard.schema.js
> +        'string',
na pewno string? hasło moze zawierac jedynie liczby, dodaj test sprawdzajacy ze 8 liter nie przechodzi

2022-03-03 06:41 UTC, lukasz-galka commented on pages/api/boards/[id]/index.test.js
> +    it('for password lenght too long', async () => {
`lenght` ?

2022-03-03 06:41 UTC, lukasz-galka commented on pages/api/boards/[id]/index.test.js
> +    it('when valid id and null password  is provided', async () => {
podwojna spacja `password  is`

2022-03-03 10:26 UTC, alexsimkovich requested changes

2022-03-03 10:26 UTC, alexsimkovich commented on pages/api/boards/[id]/__snapshots__/index.test.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
`Snapshot tests are a very useful tool whenever you want to make sure your UI does not change unexpectedly.`
a ty dodałeś snapshota do API

2022-03-05 14:33 UTC, lukasz-galka approved these changes

2022-03-06 17:13 UTC, alexsimkovich approved these changes

2022-03-16 22:24 UTC, merged