feat: P2022-1232 Characters count component
intive/patronage22_szczecin_js pull request #36
Opened 2022-02-23 01:13 UTC by karosmyr

2022-02-28 17:31 UTC, lukasz-galka requested changes

2022-02-28 17:31 UTC, lukasz-galka commented on components/CharacterCounter/CharacterCounter.js
> +}
mozesz to zapisac prosciej

```
return <p className={className} data-testid='counter'>{(inputValue || '').length}/{maxCharacters}</p>
```

nie ma sensu ifowac calego bloku, mozesz to zrobic w srodku

2022-02-28 17:31 UTC, lukasz-galka commented on components/CharacterCounter/CharacterCounter.js
> +export default function CharacterCounter ({ inputValue, maxCharacters, className }) {
daj tutaj `span`, `p` jest do wiekszych blokow tekstu

2022-02-28 17:31 UTC, lukasz-galka commented on components/BoardColumn/BoardColumn.js
> +                <StyledCharacterCounter inputValue={cardTextValue} maxCharacters={maxLength} />
jak sobie teraz o tym mysle to fajnie jakbysmy zintegrowali ten nowy komponent characterCounter z textArea i inputem, jezeli textarea/input ma maxLength zdefiniowane to counter powinien sie zawsze pojawiac, nie bedziemy musieli przekazywac 2 razy maxLength

counter powinien byc wyenderowany za textarea/inputem i miec style
```
font-size: 0.875rem;
    color: rgb(81, 81, 81);
    margin-top: 0.5rem;
```

jak wrzucisz go do boardcolumn to skasuj z textarea tam margin bottom

2022-03-01 00:44 UTC, karosmyr commented on components/CharacterCounter/CharacterCounter.test.js
> +    expect(screen.getByTestId('counter')).toHaveTextContent('9/30')
To w takim razie zmienić z
`expect(screen.getByText('9/30')).toHaveTextContent('9/30')`
na
`expect(screen.getByText('9/30')).toBeTruthy()`
? Bo chyba średni to pomysł, żebym brał po text i sprawdzał po text content

2022-03-05 14:58 UTC, lukasz-galka requested changes

2022-03-05 14:58 UTC, lukasz-galka commented on components/TextArea/style.js
> +`
wydaje mi sie ze to nie jest nam potrzebne, lepiej skasowac align items center tutaj i dac text align center na h4

![image](https://user-images.githubusercontent.com/17024927/156888437-5cb67ad5-cd67-41e4-8e81-9d4b310c8094.png)

2022-03-05 14:58 UTC, lukasz-galka commented on components/Input/style.js
> +  margin: ${props => props.maxLength ? '1rem 0 0 0' : '1rem 0'};
nie zmieniajmy marginesu w zaleznosci czy jest counter lub nie, skasuj margin bottom z inputa i zwieksz margin top na footerze z butonami, dzieki tem odleglosc pomiedzy footerem a contentem bedzie stala niezaleznie czy jest counter czy nie

2022-03-05 14:58 UTC, lukasz-galka commented on components/Input/style.js
> +`
counter powinien byc do lewej, wydaje mi sie ze znowu tutaj mamy nie potrzebnie align items center na rodzicu

2022-03-08 14:29 UTC, alexsimkovich approved these changes

2022-03-13 08:45 UTC, lukasz-galka approved these changes

2022-03-14 11:02 UTC, merged