feat: P2022-923 Remove board API
intive/patronage22_szczecin_js pull request #37
Opened 2022-02-24 11:49 UTC by grumpyjacek

Testy w drodze.

2022-02-28 10:43 UTC, grumpyjacek commented
> Testy w drodze.

Wrzucone z testami.

2022-02-28 17:45 UTC, lukasz-galka requested changes

2022-02-28 17:45 UTC, lukasz-galka commented on package.json
> +    "node-mocks-http": "1.11.0",
zrob rebase, to jest juz w main

2022-02-28 17:45 UTC, lukasz-galka commented on pages/api/boards/[id]/index.page.js
> +  res.end()
powinnismy zwracac 
204 w przypadku sukcesu
404 w przypadku gdy board nie istnieje, przy 404 powinien byc tez message w obiekcie, zobacz w tikecie i u Marcina w PR jaki obiekt on ma, tutaj bedzie obiekt jedynie z `message`

2022-03-01 08:23 UTC, alexsimkovich requested changes

2022-03-01 08:23 UTC, alexsimkovich commented on pages/api/boards/[id]/index.page.js
> +  res.end()
też bym to owrapował w try/catcha

2022-03-03 12:03 UTC, grumpyjacek commented
> > Testy w drodze.
> 
> Wrzucone z testami.

Walidacja w drodze.

2022-03-06 14:30 UTC, grumpyjacek commented on pages/api/boards/[id]/index.page.js
> +  res.end()
Ostatecznie sprawdzanie istnienia kasowanego id jest zrobione z `get()`, ponieważ `remove()` w firebase zawsze zwraca `undefined`

2022-03-07 11:49 UTC, lukasz-galka commented on pages/api/boards/[id]/index.page.js
> +  if (!lookupId.val()) return res.status(404).end()
powinienes zwrocic obiekt z message `Board with id {id} was not found`, juz to mamy odobny przyapdek tutaj https://github.com/intive/patronage22_szczecin_js/pull/30/files

2022-03-08 14:18 UTC, lukasz-galka approved these changes

2022-03-08 14:24 UTC, alexsimkovich approved these changes

2022-03-08 14:24 UTC, alexsimkovich commented on package.json
> +    "next": "12.1.0",
dobra, nie było tematu :)

2022-03-14 12:49 UTC, merged