feat: P2022-545 Add board API
intive/patronage22_szczecin_js pull request #39
Opened 2022-03-05 17:26 UTC by yusts

2022-03-08 14:19 UTC, lukasz-galka approved these changes

2022-03-08 14:25 UTC, alexsimkovich requested changes

2022-03-08 14:25 UTC, alexsimkovich commented on pages/api/boards/index.page.js
> +    name: req.query.name.trim(),
this is wrong. You should take name from `json` payload

2022-03-11 07:33 UTC, alexsimkovich approved these changes

2022-03-15 22:27 UTC, merged