WIP: Feat/p2022 264/navigate to board details
intive/patronage22_szczecin_js pull request #40
Opened 2022-03-06 12:50 UTC by AnnaSawickaZiolkowska

Dodałam WIP bo bazuję na `feat/P2022-261/render-board-details-page` , które jest jeszcze nie potwierdzone

2022-03-09 21:31 UTC, Noshi96 commented on components/ContextMenu/ContextMenu.js
> +  }
![image](https://user-images.githubusercontent.com/38572172/157538566-9425b398-7c4f-475b-8c8d-ac94e6ceba10.png)
Raczej nie powinno się tak zachowywać context menu, ale jak się zmieni na `e.preventDefault()` to będzie tak jak wcześniej czyli tylko jedno context menu będzie mogło być otwarte w tym samym czasie.

2022-03-16 13:49 UTC, lukasz-galka requested changes

2022-03-16 13:49 UTC, lukasz-galka commented on components/BoardTile/BoardTile.js
> +    <Link href={`/boards/${id}`} key={id} passHref>
a gdzie link? w htmlu powinien byc wygeneroany `a` element

2022-03-16 13:49 UTC, lukasz-galka commented on components/BoardTile/BoardTile.js
> +    <Link href={`/boards/${id}`} key={id} passHref>
po co ten `key` ?

2022-03-16 13:49 UTC, lukasz-galka commented on components/BoardTile/BoardTile.js
> +        <Header>{name}</Header>
mozemy dodac jakies testy aby sprawdzic ze dziala przekierowanie na detale?

2022-03-19 20:44 UTC, Noshi96 commented on components/BoardTile/BoardTile.js
> +        <Header>{name}</Header>
![image](https://user-images.githubusercontent.com/38572172/159137614-afe14ba3-7781-4bf1-8b56-f46bcb7d6188.png)
Przez to, że generuje nam się ` <a> ` w htmlu to mamy te podkreślenia. Można dodać 
```css
text-decoration: none;
```
 w stylach do 
 ```javascript
 <Tile>
 ```
żeby się tego pozbyć

2022-03-22 17:00 UTC, lukasz-galka requested changes

2022-03-22 17:00 UTC, lukasz-galka commented on components/BoardTile/BoardTile.js
> +        <Header>{name}</Header>
czemu to bylo rozwiazane? mamy juz test pod to?

2022-03-27 08:52 UTC, lukasz-galka approved these changes

2022-03-27 11:44 UTC, merged