feat: P2022-1616 Get board details API
intive/patronage22_szczecin_js pull request #45
Opened 2022-03-17 18:06 UTC by grumpyjacek

2022-03-22 17:09 UTC, lukasz-galka commented on pages/api/boards/[id]/index.page.js
> +  const foundId = await lookupId.val()
czy to nie jest po prostu board?

2022-03-22 17:09 UTC, lukasz-galka commented on pages/api/boards/[id]/index.page.js
> +  const board = [foundId].map(item => ({
czemu tutaj ten map? przeciez mamy tylko jeden board?

2022-03-22 17:10 UTC, lukasz-galka commented on pages/api/boards/[id]/index.page.js
> +  const columnsArr = (columns) => {
to mowi Ci nazwa tej funkcji columnsArr? bo mi nic

2022-03-22 17:13 UTC, lukasz-galka commented on pages/api/boards/[id]/index.page.js
> +    hasPassword: !!item.password,
czy has Password dziala dobrze? sprawdz odpowiedz z API

2022-03-23 09:11 UTC, grumpyjacek commented on pages/api/boards/[id]/index.page.js
> +  const columnsArr = (columns) => {
zmienię na boardColumns

2022-03-23 09:31 UTC, grumpyjacek commented on pages/api/boards/[id]/index.page.js
> +  const foundId = await lookupId.val()
board :)

2022-03-23 09:34 UTC, grumpyjacek commented on pages/api/boards/[id]/index.page.js
> +    hasPassword: !!item.password,
Odpowiedzi mam dobre, problem jest z pobieraniem haseł na stronę główną z `pages/api/boards/index.page.js` . Sprawdzę, czy to już jest naprawione i jeśli tak, to zrobię rebase, jeśli nie - to poprawię .

2022-03-26 08:53 UTC, lukasz-galka requested changes

2022-03-26 08:53 UTC, lukasz-galka commented on pages/api/boards/[id]/index.test.js
> +    })
w bazie nie mamy id przy boardzie, czyli jak pytasz o konkretny board to nie dostaniesz id w odpowiedzi, dla password wykorzystaj tez poprawny format danych

2022-03-26 08:53 UTC, lukasz-galka commented on pages/api/boards/[id]/index.test.js
> +        id: 'ABC567'
korzystaj z poprawnego formatu id

2022-03-26 08:53 UTC, lukasz-galka commented on pages/api/boards/[id]/index.test.js
> +      columns: [
to nie jest poprawna odpowiedz z bazy, w bazie columns jest obiektem jak

```
columns: {
  "01FZ2P5JDEYDFPWXNVJ1KR2BRD": {
    "name": ...,
    "cards": []
  }
}
```

tak samo dla cards, tam test jest obiekt - kod dziala dobrze

te testy aktualnie dzialaja Ci przez przypadek... zmien sobie w mocku id z 0 na 10 i tez przejda, poniewaz na wyjsciu bedzie i tak 0 bo robisz object entries na tablicy a nie obiekcie

2022-03-26 16:08 UTC, grumpyjacek commented on pages/api/boards/[id]/index.test.js
> +      columns: [
poprawione

2022-03-27 08:57 UTC, lukasz-galka approved these changes

2022-03-27 11:43 UTC, merged