feat: P2022-1617 Add column API
intive/patronage22_szczecin_js pull request #47
Opened 2022-03-18 01:13 UTC by karosmyr

Po zrobieniu rebase z mainem nie przechodzi checków. Jak wejdzie fix to zrobie rebase.

2022-03-19 20:55 UTC, Noshi96 commented on pages/api/boards/[id]/columns/index.page.js
> +  }
Jak pushujemy niezależnie od warunku to `else` jest niepotrzebny

2022-03-19 20:55 UTC, Noshi96 commented on pages/api/boards/[id]/columns/index.page.js
> +  }
Jak pushujemy niezależnie od warunku to `else` jest niepotrzebny

2022-03-22 17:21 UTC, lukasz-galka requested changes

2022-03-22 17:21 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/index.page.js
> +  patch: addColumn
czemu patch? ma dzialac na post

2022-03-22 17:21 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/index.page.js
> +    await update(child(ref(database), `${dbPrefix}/boards/${id}`), { columns: boardData.columns })
powinienes zrobic tutaj po prostu push na columns
await push(child(ref(database), `${dbPrefix}/boards/${id}/columns`), data)

2022-03-26 09:16 UTC, lukasz-galka approved these changes

2022-03-26 09:20 UTC, lukasz-galka requested changes

2022-03-26 09:20 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/index.test.js
> +    snapshot.val.mockResolvedValue({
jak pytasz o board po id to nie dostaniesz tego id, wiec w mockowym responsie powinno byc jedynie
```
{
        name: 'board 1',
        createdAt: '2000-01-01T00:00:00.000Z'
      }
```

2022-03-27 08:59 UTC, lukasz-galka approved these changes

2022-03-28 13:15 UTC, merged