feat: P2022-1618 Add card API
intive/patronage22_szczecin_js pull request #48
Opened 2022-03-19 17:51 UTC by Noshi96

2022-03-21 14:20 UTC, karosmyr commented on schema/addCard.schema.js
> +    text: {
`    id: {
      type: 'string'
    },`
Można usunąć

2022-03-22 17:26 UTC, lukasz-galka requested changes

2022-03-22 17:26 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[idColumn]/cards/index.page.js
> +  patch: addCard
powinien byc post, zobacz co pisalem tutaj https://github.com/intive/patronage22_szczecin_js/pull/43

2022-03-22 17:26 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[idColumn]/cards/index.page.js
> +  if (!text) {
potrzebny ten warunek? czy to nie zostanie sprawdzone przez walidacje schemy nizej?

2022-03-22 17:26 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[idColumn]/cards/index.page.js
> +  const columnLookupId = await get(child(ref(database), `${dbPrefix}/boards/${id}/columns`))
nie mozesz od razu pobrac columny przy get?

2022-03-22 17:26 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[idColumn]/cards/index.page.js
> +  const { id, idColumn } = req.query
parametr nazwijmy `column-id`

2022-03-22 17:45 UTC, Noshi96 commented on pages/api/boards/[id]/columns/[idColumn]/cards/index.page.js
> +  if (!text) {
Chcę żeby to sprawdzało czy w body requesta parametr faktycznie nazywa się "text", a nie np "text111", tak żeby zwróciło dzięki temu ifowi "Bad request". Podobnie to też wyłapuje czy w body "text": null i wtedy też zwraca "Bad request"

2022-03-22 17:51 UTC, Noshi96 commented on pages/api/boards/[id]/columns/[idColumn]/cards/index.page.js
> +  const columnLookupId = await get(child(ref(database), `${dbPrefix}/boards/${id}/columns`))
Problem jest taki, że w tym momencie po /columns/ mamy index tablicy, a nie id kolumny 
```javascript
const columnLookupId = await get(child(ref(database), `${dbPrefix}/boards/${id}/columns/${columnIndex}`))
```
a w requescie przekazujemy columnId, a nie index

2022-03-23 12:43 UTC, Noshi96 commented on pages/api/boards/[id]/columns/[idColumn]/cards/index.page.js
> +  if (!text) {
nvm musiałem dodać do schema `required: ['text']` i zmienić 
```javascript
text: req.body.text.trim()
```
na
```javascript
text: req.body.text?.trim()
```
teraz faktycznie waliduje się w schema

2022-03-24 07:54 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[idColumn]/cards/index.page.js
> +  const columnLookupId = await get(child(ref(database), `${dbPrefix}/boards/${id}/columns`))
ale w bazie columns to nie jest tablica a obiekt z kluczami

2022-03-24 11:37 UTC, Noshi96 commented on pages/api/boards/[id]/columns/[idColumn]/cards/index.page.js
> +  const columnLookupId = await get(child(ref(database), `${dbPrefix}/boards/${id}/columns`))
no to u nas tak nie było 
![image](https://user-images.githubusercontent.com/38572172/159908142-ed2f157f-2536-49fc-a634-1238bd147245.png)

2022-03-26 08:11 UTC, lukasz-galka requested changes

2022-03-26 08:11 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[columnId]/cards/index.test.js
> +
tutaj szukasz jednej kolumny po id
```
const currentColumn = await get(child(ref(database), `${dbPrefix}/boards/${id}/columns/${columnId}`))
```
a w mocku zwraszasz liste, mock powinien zwrocic jedynie jedna kolumne jak
```
{cards: [], name: ....}
```

id tutaj tez nie ma, bo jak pamietasz id jest w kluczu jak
```
id: {
name: ...
cards: ...
```

2022-03-26 08:11 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[columnId]/cards/index.test.js
> +        const id = '-MyUHzvYNsNejyv1_4Zj'
id boardy powinno tez byc ulidem

2022-03-26 11:57 UTC, Noshi96 commented on pages/api/boards/[id]/columns/[columnId]/cards/index.test.js
> +
Jasne, moje niedopatrzenie z tym, że mock teraz nie powinien zwracać listy :D

2022-03-26 12:12 UTC, lukasz-galka approved these changes

2022-03-28 20:26 UTC, merged