feat: P2022-1619 Remove column API
intive/patronage22_szczecin_js pull request #49
Opened 2022-03-19 21:01 UTC by karosmyr

2022-03-19 22:03 UTC, Noshi96 commented on pages/api/boards/[id]/columns/[columnId]/index.test.js
> +    snapshot.val.mockResolvedValue(Promise.all([
Testowałem to jeszcze raz i jednak nie jest potrzebny ten Promise.all() xd

2022-03-19 22:03 UTC, Noshi96 commented on pages/api/boards/[id]/columns/[columnId]/index.test.js
> +    snapshot.val.mockResolvedValue(Promise.all([
Testowałem to jeszcze raz i jednak nie jest potrzebny ten Promise.all() xd

2022-03-22 17:27 UTC, lukasz-galka requested changes

2022-03-22 17:27 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[columnId]/index.page.js
> +  const columnLookupId = await get(child(ref(database), `${dbPrefix}/boards/${id}/columns`))
wez od razu columne w get

2022-03-22 17:27 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[columnId]/index.page.js
> +    const indexToRemove = columnData.findIndex(item => item.id === columnId)
po prostu skasuj ta kolumne po id, nie musisz czyscic columns,

2022-03-26 09:21 UTC, lukasz-galka requested changes

2022-03-26 09:21 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[columnId]/index.test.js
> +    snapshot.val.mockResolvedValue({
jak pyasz o columne po id to dostaniesz jedynie name
```
{
name: ...
}
```

2022-03-27 09:01 UTC, lukasz-galka approved these changes

2022-03-28 23:50 UTC, merged