feat: P2022-1230 Set password on board
intive/patronage22_szczecin_js pull request #50
Opened 2022-03-21 00:34 UTC by yusts

Testy wkrótce zostaną dodane

2022-03-21 13:04 UTC, Noshi96 commented on components/BoardTile/BoardTile.js
> +  }
Wydaje mi się, że ta funkcja jest niepotrzebna bo możesz sobie zainicjalizować boardId w useState jak się generuje komponent
```javascript
const [boardId] = useState(id)
```

2022-03-21 13:23 UTC, Noshi96 commented on components/Toast/Toast.test.js
> +    })
A to jest akurat ciekawe bo jakbyśmy chcieli bez `act()` to w górnych testach trzeba by dodać `waitFor(() => { expect(baseElement).toMatchSnapshot() })`. Nie wiem co lepiej używać xd

2022-03-21 13:35 UTC, yusts commented on components/Toast/Toast.test.js
> +    })
W sumie tutaj można o tym poczytać:
https://davidwcai.medium.com/react-testing-library-and-the-not-wrapped-in-act-errors-491a5629193b

2022-03-24 21:15 UTC, yusts commented
@alexsimkovich @lukasz-galka

2022-03-26 12:31 UTC, lukasz-galka requested changes

2022-03-26 12:31 UTC, lukasz-galka commented on components/BoardTile/BoardTile.js
> +  const [isOpen, setIsOpen] = useState(false)
isOpen ale co? dodaj jakies wiekszy opis, bo co jak dodamy drugi modal?

2022-03-26 12:31 UTC, lukasz-galka commented on services/internal-api/index.js
> +
musisz poczekac na zmergowanie zmian od Marcina https://github.com/intive/patronage22_szczecin_js/pull/38 tam juz mamy updateBoard

2022-03-26 12:31 UTC, lukasz-galka commented on components/Modal/Modal.test.js
> +  it('if password length less than 8, should not close Modal after click on save button', () => {
co tutaj robia testy od hasla? to jest ogolny komponent modal, tutaj nie powinno byc nic zwiazanego z haslem

2022-03-27 15:14 UTC, alexsimkovich requested changes

2022-03-27 15:14 UTC, alexsimkovich commented on components/SetPasswordModal/SetPasswordModal.js
> +    if (event.target.value === '' || onlyDigitsRegex.test(event.target.value)) {
Dlaczego ten warunek `event.target.value === ''` ?

2022-03-27 15:14 UTC, alexsimkovich commented on components/SetPasswordModal/SetPasswordModal.js
> +  useEffect(() => {
Dlaczego ten useEffect i ustawienia Hasła na `''` ?

2022-03-27 15:20 UTC, alexsimkovich requested changes

2022-03-27 15:20 UTC, alexsimkovich commented on components/BoardTilesList/BoardTilesList.js
> +      onClick={onClick}
Przekazałeś tutaj `onClick`, ale w samym BoardTile nie używasz tego. Czy jest to potrzebne w takim razie?

2022-03-27 15:20 UTC, alexsimkovich commented on components/SetPasswordModal/SetPasswordModal.js
> +      disabled={password.length < 8}
Normalnie, to powinno być w globalnym context-cie. Nie możemy dodawać niewiadomo ile propsów za każdym razem jak coś nowego będzie potrzebne

2022-03-27 15:45 UTC, yusts commented on components/BoardTilesList/BoardTilesList.js
> +      onClick={onClick}
Usunąłem

2022-03-27 15:45 UTC, yusts commented on components/SetPasswordModal/SetPasswordModal.js
> +  useEffect(() => {
Aby po zamknięciu SetPasswordModal pole tekstowe zostało wyczyszczone

2022-03-27 15:45 UTC, yusts commented on components/SetPasswordModal/SetPasswordModal.js
> +    if (event.target.value === '' || onlyDigitsRegex.test(event.target.value)) {
W sumie nie jest potrzebny, usunąłem

2022-04-01 10:48 UTC, lukasz-galka requested changes

2022-04-01 10:48 UTC, lukasz-galka commented on components/SetPasswordModal/SetPasswordModal.js
> +export default function SetPasswordModal ({ handleClose, isSetPasswordModalOpen, boardId }) {
jak juz jestes w jego kontekscie to on powinien przyjmowac pros `isModalOpen`

2022-04-01 10:48 UTC, lukasz-galka commented on components/Modal/Modal.js
> +  const closeModal = () => {
na click w save button bym wywolal handle save i dopiero tam zamknal modal,a tutaj bez try catch

2022-04-02 22:58 UTC, yusts commented on components/SetPasswordModal/SetPasswordModal.js
> +    if (event.target.value === '' || onlyDigitsRegex.test(event.target.value)) {
Przegapiłem, jest jednak potrzebne, inaczej nie da się usunąć wprowadzone dane. Pozostanie jeden symbol, który nie da się usunąć.

2022-04-03 07:54 UTC, lukasz-galka requested changes

2022-04-03 07:54 UTC, lukasz-galka commented on components/Modal/__snapshots__/Modal.test.js.snap
> +<body>
czemu ten plik jest pusty?

2022-04-03 08:14 UTC, yusts commented on components/Modal/__snapshots__/Modal.test.js.snap
> +<body>
Poprawiono

2022-04-04 15:52 UTC, lukasz-galka approved these changes

2022-04-06 05:32 UTC, merged