WIP! feat: P2022-1620 Remove card api
intive/patronage22_szczecin_js pull request #51
Opened 2022-03-21 21:28 UTC by AnnaSawickaZiolkowska

2022-03-25 15:45 UTC, Noshi96 commented on pages/api/boards/[id]/columns/[ColumnId]/cards/[CardId]/index.page.js
> +    await update(child(ref(database), `${dbPrefix}/boards/${id}/columns/${columnId}`), { boards: cardData })
Z Konradem zmieniamy u siebie i będzie już normalnie można zrobić `get` na `/.../${columnsId}/cards/${cardId}` i sprawdzić czy istnieje konkretna kartka i potem już zwykły remove myślę, że będzie spoko
```javascript
await remove(child(ref(database), `${dbPrefix}/boards/${id}/columns/${columnId}/cards/${cardId}`))
```

2022-03-27 09:12 UTC, lukasz-galka requested changes

2022-03-27 09:12 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[ColumnId]/cards/[CardId]/index.page.js
> +import { dbConnect, dbPrefix } from '../../../../../../../../libs/dbClient'
daj nazwy folderow jak `columnId` a nie `ColumnId`

2022-03-27 09:12 UTC, lukasz-galka commented on pages/api/boards/[id]/columns/[ColumnId]/cards/[CardId]/index.test.js
> +})
co to za puste pliki ponizej?

2022-03-27 14:11 UTC, Noshi96 commented on pages/api/boards/[id]/columns/[columnId]/cards/[cardId]/index.test.js
> +    const cardId = 333
Tak jak Łukasz pisał u Jacka powinniśmy korzystać z poprawnego formatu id https://github.com/intive/patronage22_szczecin_js/pull/45#discussion_r835739317
np 01FV757GXRK6A9MMFA1EMA2V7D

2022-03-27 18:29 UTC, AnnaSawickaZiolkowska commented
Ooo super, dziękuję za info...nie zauważyłam tego komentarza 🙂

niedz., 27 mar 2022, 16:12 użytkownik Noshi96 ***@***.***>
napisał:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In pages/api/boards/[id]/columns/[columnId]/cards/[cardId]/index.test.js
> <https://github.com/intive/patronage22_szczecin_js/pull/51#discussion_r835913610>
> :
>
> > +    const id = 111
>
> +    const columnId = 222
>
> +    const cardId = 333
>
>
> Tak jak Łukasz pisał u Jacka powinniśmy korzystać z poprawnego formatu id #45
> (comment)
> <https://github.com/intive/patronage22_szczecin_js/pull/45#discussion_r835739317>
> np 01FV757GXRK6A9MMFA1EMA2V7D
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/intive/patronage22_szczecin_js/pull/51#pullrequestreview-922457077>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASNC2EIF6MPTP4RPYPTSB4TVCB3EFANCNFSM5RI7DOWA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-01 07:09 UTC, lukasz-galka approved these changes

2022-04-02 13:26 UTC, merged