feat: P2022-1612 Show toast after removing board
intive/patronage22_szczecin_js pull request #53
Opened 2022-03-24 21:08 UTC by Noshi96

2022-03-26 09:49 UTC, alexsimkovich requested changes

2022-03-26 09:49 UTC, alexsimkovich commented on components/BoardTile/BoardTile.js
> +    }
Poczekaj aż Marcin zmerguje swoje. Ja bym to wszystko owrapowałbym w try/catch statement

2022-03-26 09:49 UTC, alexsimkovich commented on components/BoardTile/MockBoardTile.js
> +export default function MockBoardTile ({ id, name, date, cardCount, hasPassword }) {
Dlaczego nam jest potrzebny MockBoardTile?

2022-03-26 11:03 UTC, Noshi96 commented on components/BoardTile/MockBoardTile.js
> +export default function MockBoardTile ({ id, name, date, cardCount, hasPassword }) {
Toast ma się pokazywać w momencie pozytywnej operacji usuwanie boarda, czyli gdy status requesta będzie równy 204. Problem jest taki, że w testach operacja `await deleteBoard(id)` nie wykonuje się, czyli nie zwraca mi statusu, po którym mógłbym sprawdzić czy pozytywny toast się wyświetla. Mockuje BoardTile, żeby móc ustawić zmockowany status, żeby sprawdzić czy czy przy 204 wyświetli się pozytywny toast, a przy innym statusie niż 204 wyświetli się error toast.

2022-03-28 21:50 UTC, Noshi96 commented on components/BoardTile/BoardTile.js
> +    }
Dodałem try catche

2022-04-01 10:55 UTC, lukasz-galka requested changes

2022-04-01 10:55 UTC, lukasz-galka commented on components/BoardTile/BoardTile.test.js
> +    render(<MockBoardsContextProvider />)
a nie mozesz po prostu zamokowac opdowiedzi z api https://jestjs.io/docs/mock-function-api#mockfnmockresolvedvaluevalue ?

2022-04-01 10:55 UTC, lukasz-galka commented on store/boards-context.js
> +  showSuccessToast: () => {},
nie podoba mi sie umieszczenie tego w kontekscie boardu, nie ma lepszego rozwiazania?

2022-04-01 17:10 UTC, Noshi96 commented on store/boards-context.js
> +  showSuccessToast: () => {},
Zrobiłem osobny context dla toasta

2022-04-04 21:58 UTC, Noshi96 commented on components/BoardTile/BoardTile.js
> +    } catch (error) { console.error(error) }
Działa :)
![image](https://user-images.githubusercontent.com/38572172/161638895-dc847c65-4b45-4547-8bb8-0dde7814a792.png)

2022-04-04 23:27 UTC, Noshi96 commented on components/BoardTile/BoardTile.test.js
> +      render(<MockToastsContextProvider status={res._getStatusCode()} />)
Pomysł był taki, żeby można było wywoływać sobie Toast z dowolnego miejsca w kodzie bez ingerencji w kod renderowanego komponentu. W tym momencie `<ToastsContextProvider>` owrapowuje nam wszystkie boardy w głównym pliku `index.page.js`.
```javascript
      <Layout>
        <ToastsContextProvider>
          <BoardsContextProvider boards={tilesList}>
            <BoardTilesList tilesList={tilesList} />
          </BoardsContextProvider>
        </ToastsContextProvider>
      </Layout>
```
 Sam komponent Toast jest wywoływany pod `porps.children` w pliku `toasts-context.js` .
```javascript
  return (
    <ToastsContext.Provider value={context}>
      {props.children}
      {isOpenToast && <RenderToast />}
    </ToastsContext.Provider>
  )
```
Wyrenderowanie w testach `<MockBoardTile>` i wciśnięcie przycisku sprawi, że `<Toast>` się wywoła, ale poza scopem więc nie widzę tego toasta. Dlatego mockuje `<MockToastsContextProvider>`, żeby widzieć `<Toast>` po wciśnięciu przycisku.

Z kolei `<MockBoardTile>` mockuje bo jestowe testy w `<BoardTile>` zatrzymują się gdy wywołujemy `await deleteBoard(id)` w handlerze, który jest podpięty pod przycisk usuwania więc nawet nie dojdzie do ifa sprawdzającego `status`.

![image](https://user-images.githubusercontent.com/38572172/161646914-45ad62ab-ff21-4935-90e7-248196b3af82.png)
![image](https://user-images.githubusercontent.com/38572172/161646965-0eb392c4-11e9-48aa-a924-cab43232b502.png)

W `<MockBoardTile>` oczekuje na status żeby móc wyświetlić Toasta przez wywołanie funkcji z contextu z pominięciem metody `await deleteBoard(id)`.
```javascipt
  async function deleteBoardHandler (id) {
    const data = { status: id }
    if (data.status === 204) {
      toastsCtx.showSuccessToast(toastMessage.success)
    } else {
      toastsCtx.showErrorToast(toastMessage.error)
    }
  }
```
Jak na razie nie mam pomysłu na sprawdzenie tego bez mock context i mock tile.

2022-04-07 05:30 UTC, lukasz-galka approved these changes

2022-04-07 11:18 UTC, merged