feat: P2022-65 Add board tile
intive/patronage22_szczecin_js pull request #6
Opened 2022-01-19 20:15 UTC by grumpyjacek

No icons available yet, so I used X instead of a padlock icon.

2022-01-20 10:59 UTC, alexsimkovich commented
@grumpyjacek please refer to https://www.educative.io/blog/best-practices-react-developer (react components naming convention). Thanks

2022-01-20 11:00 UTC, alexsimkovich requested changes

2022-01-20 11:00 UTC, alexsimkovich commented on pages/index.page.js
> +        <BoardTile name={'Board name 1'} date={'1 Jan 2022'} cardNumber={'0'} />
if props has static data, `{}` are redundant. Just `name='Board name 1'` , etc...

2022-01-20 11:00 UTC, alexsimkovich commented on styles/global.css
> +  font-family: Roboto, sans-serif;
Where do we have this fonts initialized?

2022-01-20 11:00 UTC, alexsimkovich commented on components/board-tile/__snapshots__/board-tile.test.js.snap
> +  "debug": [Function],
Hmm, i think this is something we don't need here!?

2022-01-20 12:19 UTC, lukasz-galka commented on styles/global.css
> +  padding: 0;
po co ten margin/padding?

2022-01-20 12:27 UTC, lukasz-galka commented on components/board-tile/style.js
> +  box-shadow: 0 2px 6px rgba(98, 98, 98, 0.21);
w sumie mozemy to pominac, dodamy to jak bedziemy robic przekierowania na detale boarda...

2022-01-20 14:11 UTC, grumpyjacek commented on styles/global.css
> +  padding: 0;
Chciałem wyzerować domyślne ustawienia marginesów przeglądarek, żeby było spójnie.

2022-01-20 14:13 UTC, alexsimkovich commented on styles/global.css
> +  padding: 0;
@grumpyjacek ale my już mamy podłączony `normalize.css` który to ogrania

2022-01-20 14:17 UTC, lukasz-galka requested changes

2022-01-20 14:17 UTC, lukasz-galka commented on components/board-tile/board-tile.test.js
> +    expect(Tile).toMatchSnapshot()
daj `Tile.container`, nie potrzebujemy pozostalych elementow

2022-01-20 14:17 UTC, lukasz-galka commented on components/board-tile/board-tile.js
> +export default function BoardTile({name, date, cardNumber}) {
zamien `cardNumer` na `cardsCount`, oraz dodaj parametr `hasPassword` i on powinien decydowac czy ikonka sie pojawia czy nie

2022-01-20 14:17 UTC, lukasz-galka commented on components/board-tile/board-tile.test.js
> +    const Tile = render(<BoardTile />)
podaj parametry aby sprawdzic czy renderuja sie prawidlowo, powinien tez byc drugi test ktory nie ma ikonki od hasła

2022-01-20 14:55 UTC, grumpyjacek commented on styles/global.css
> +  padding: 0;
@alexsimkovich a to trzeba u siebie importować, czy działa prosto z pudełka?
 Jak zdejmę z globall.css margin/padding, to w Chromie dostaję domyślnie marginesy 12px, pomimo że w normlaize.css jest  body {
  margin: 0;
}
Dziękuję za pomoc :)

2022-01-20 14:58 UTC, alexsimkovich commented on styles/global.css
> +  padding: 0;
@grumpyjacek to już jest zaimportowane w `_app.page.js`. @lukasz-galka to dodał ;)

2022-01-20 16:48 UTC, grumpyjacek commented on styles/global.css
> +  padding: 0;
@lukasz-galka, robiłem `npm install` po zaciągnięciu zmian. Opróżnię node_modules i spróbuję ponownie. Faktycznie na vercelu pokazuje, że wykorzystywany jest margin z `body` a nie ode mnie z `*`.Z kolei u mnie na Chrome oraz Edge nie łapało marginesu z `normalize.css`. Sprawdzę raz jeszcze wszystko.

2022-01-21 12:50 UTC, grumpyjacek commented on pages/index.page.js
> +        <BoardTile name={'Board name 1'} date={'1 Jan 2022'} cardNumber={'0'} />
Done.

2022-01-21 12:50 UTC, grumpyjacek commented on styles/global.css
> +  font-family: Roboto, sans-serif;
Initialization added.

2022-01-21 12:50 UTC, grumpyjacek commented on components/board-tile/style.js
> +  margin-bottom: 0.25rem;
Przegapiłem - już dodane.

2022-01-21 12:51 UTC, grumpyjacek commented on components/board-tile/style.js
> +  bottom: 10.75rem;
Zrobione.

2022-01-21 12:51 UTC, grumpyjacek commented on styles/global.css
> +  padding: 0;
Dodałem do globala.

2022-01-21 12:51 UTC, grumpyjacek commented on styles/global.css
> +  font-size: 16px;
Usunięte.

2022-01-21 12:51 UTC, grumpyjacek commented on components/board-tile/board-tile.test.js
> +    expect(Tile).toMatchSnapshot()
Dodane.

2022-01-21 12:52 UTC, grumpyjacek commented on components/board-tile/board-tile.js
> +export default function BoardTile({name, date, cardNumber}) {
Zrobione.

2022-01-21 12:52 UTC, grumpyjacek commented on components/board-tile/board-tile.test.js
> +    const Tile = render(<BoardTile />)
Zrobione.

2022-01-21 13:38 UTC, lukasz-galka requested changes

2022-01-21 13:38 UTC, lukasz-galka commented on components/BoardTile/Style.js
> +  top: -0.8rem;
na designie widze `12px` roznicy, wiec `-0.75rem`

2022-01-21 13:38 UTC, lukasz-galka commented on components/BoardTile/BoardTile.test.js
> +    const Tile = render(<BoardTile name date cardCount />)
przekaz wartosci dla `name` `date` i `cardCount` tak abysmy widzieli ze dobrze sie renderuja

2022-01-21 13:39 UTC, lukasz-galka commented on components/BoardTile/Style.js
> +import styled from 'styled-components'
daj prosze jeszcze `style.js` z małej

2022-01-21 14:57 UTC, alexsimkovich requested changes

2022-01-21 14:57 UTC, alexsimkovich commented on components/BoardTile/BoardTile.js
> +      {isIconVisible}
it sounds like a condition only. I would rather do like this: `{ hasPassword ? <Icon>X</Icon> : null }`. React prefers/requires `null` if we don't wan't to render anything in the DOM

2022-01-21 16:42 UTC, grumpyjacek commented on components/BoardTile/Style.js
> +  top: -0.8rem;
Przegapiłem i dawałem na oko :) Zrobione.

2022-01-21 16:43 UTC, grumpyjacek commented on components/BoardTile/BoardTile.test.js
> +    const Tile = render(<BoardTile name date cardCount />)
Zrobione.

2022-01-21 16:43 UTC, grumpyjacek commented on components/BoardTile/Style.js
> +import styled from 'styled-components'
Poprawione.

2022-01-21 16:43 UTC, grumpyjacek commented on components/BoardTile/BoardTile.js
> +      {isIconVisible}
Changed.

2022-01-21 17:41 UTC, lukasz-galka commented on styles/global.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');
myslalem ze pisalem o tym, ale musialo mi uciec, moglbys przeniesc ladowanie fontow do sekcji head? a tak pozatym to super, musimy tylko poczekac na komponent `Icon`

2022-01-22 21:02 UTC, grumpyjacek commented on styles/global.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');
Przeniosłem do head w index.page.js.

2022-01-24 09:03 UTC, lukasz-galka commented on components/BoardTile/style.js
> +
mozemy pominac stylowanie ikonki i troche uproscic 

```
export const IconWrapper = styled.div`
  position: absolute;
  right: 0.5rem;
  top: -0.75rem;
  width: 2.5rem;
  height: 2.5rem;
  border-radius: 50%;
  background-color: #E1E1E1;
  color: #515151;
  padding: 0.5rem;
`
```

2022-01-24 09:43 UTC, alexsimkovich approved these changes
👍

2022-01-24 09:49 UTC, grumpyjacek commented on components/BoardTile/style.js
> +
Poprawione :)

2022-01-25 16:14 UTC, lukasz-galka approved these changes

2022-01-31 08:18 UTC, merged