feat: P2022-943 Render columns list
intive/patronage22_szczecin_js pull request #60
Opened 2022-03-29 12:16 UTC by grumpyjacek

2022-04-01 07:07 UTC, lukasz-galka requested changes

2022-04-01 07:07 UTC, lukasz-galka commented on components/BoardColumnsList/style.js
> +  position: absolute;
czy my potrzebujemy te style w widoku moblnym jak jest jedna kolumna? wydaje mi sie ze nie, i to duzo psuje, mozemy je ustawic od widoku gdzie mamy wiele kolumn obok siebie

2022-04-01 11:36 UTC, grumpyjacek commented on components/BoardColumn/__snapshots__/BoardColumn.test.js.snap
> +      />
aj, przegapiłem

2022-04-01 12:13 UTC, grumpyjacek commented on pages/index.page.js
> +          <BoardColumn />
Przy przewijaniu poziomym Board Header nie przesuwał się, dlatego wrzuciłem te zmiany. Zobaczę, czy da radę inaczej.

2022-04-01 13:24 UTC, grumpyjacek commented on components/BoardColumnsList/style.js
> +  position: absolute;
Tak na szybko: po likwidacji tego, pasek z nazwą tablicy też się przewija. IMO na mobilkach to nawet lepiej, bo jest więcej miejsca na treść, ale nie wiem, jak to powinno się u nas zachowywać?

2022-04-02 08:06 UTC, lukasz-galka commented on pages/index.page.js
> +          <BoardColumn />
tutaj mi chodzilo tylko aby skasowac board column ze strony glownej

2022-04-02 08:06 UTC, lukasz-galka commented on components/BoardColumnsList/style.js
> +  position: absolute;
tak jak rozmawialismy na slaku, board header ma sie przewijac

2022-04-02 08:24 UTC, grumpyjacek commented on pages/index.page.js
> +          <BoardColumn />
Mój komentarz to w ogóle nie do tego miejsca miał być :)

2022-04-02 09:56 UTC, grumpyjacek commented on components/BoardHeader/style.js
> +  @media only screen and ${breakpoint.s} {
(chyba) działa

2022-04-02 13:23 UTC, lukasz-galka requested changes

2022-04-02 13:23 UTC, lukasz-galka commented on components/BoardHeader/style.js
> +export const StyledButton = styled(Button)`
czemu ta zmiana styli od buttona?

2022-04-02 13:23 UTC, lukasz-galka commented on components/BoardColumn/style.js
> +    display: inline-flex;
po co tutaj ten inline flex? ja o tym pisalem dla calej listy, tutaj aktualnie powoduje dodatkowa przestrzen
![image](https://user-images.githubusercontent.com/17024927/161385267-9f061f63-6a4c-4b3e-92d6-fb9e4dbf3ec7.png)

zobacz ze pomiedzy add carda a pierwsza kartka jest wieksza przerwa niz pomiedzy 1 i 2 kartka

2022-04-02 14:06 UTC, grumpyjacek commented on components/BoardHeader/style.js
> +export const StyledButton = styled(Button)`
a to pozostałości po wcześniejszych przeróbkach - usuwam

2022-04-02 14:10 UTC, grumpyjacek commented on components/BoardColumn/style.js
> +    display: inline-flex;
faktycznie - poprawione, chociaż imo z tą przerwą wyglądało ładniej ;)

2022-04-03 07:38 UTC, lukasz-galka requested changes

2022-04-03 07:38 UTC, lukasz-galka commented on components/BoardHeader/style.js
> +  font-size: 1.2rem;
a ta zmiana to po co?

2022-04-03 07:39 UTC, lukasz-galka approved these changes

2022-04-03 09:09 UTC, grumpyjacek commented on components/BoardHeader/style.js
> +  font-size: 1.2rem;
przemknęło pod radarem :)

2022-04-06 09:11 UTC, merged