Feat/p2022 62/add header component
intive/patronage22_szczecin_js pull request #8
Opened 2022-01-20 01:33 UTC by karosmyr

2022-01-20 12:54 UTC, lukasz-galka requested changes

2022-01-20 12:54 UTC, lukasz-galka commented on components/layout/header.js
> +const HeaderContainer = styled.div`
przeniesc style do osobnego pliku

2022-01-20 12:54 UTC, lukasz-galka commented on components/layout/header.js
> +
czemu `div` a nie `header` ? staraj sie korzystac z semantic html

2022-01-20 12:54 UTC, lukasz-galka commented on components/layout/header.js
> +  color: #222222;
jeżeli potrzebujesz jedynie margines po lewej stronie, to uzywaj `margin-left`

2022-01-20 12:54 UTC, lukasz-galka commented on components/layout/header.js
> +  width: 100%;
use rem for font-size, line-height, margin, padding

2022-01-20 14:18 UTC, lukasz-galka commented on components/layout/header.test.js
> +    expect(header).toMatchSnapshot()
w snapshotach sprawdzaj jedynie `container`, przykładowow `header.container`

2022-01-20 15:46 UTC, karosmyr commented on components/layout/header.js
> +const HeaderContainer = styled.div`
Jak powinien nazywać się plik? Jeżeli mam dwa componenty 'Header.js' i 'Layout.js' to powinienem w tym subfolderze mieć jeden plik style.js czy Header.style.js i Layout.style.js?

2022-01-21 08:09 UTC, lukasz-galka commented on components/layout/header.js
> +const HeaderContainer = styled.div`
ogolnie komponenty powinny byc na plasko, wiec `components/Header` i `components/Layout`, plik od styli wrzuc w `style.js`

2022-01-21 08:09 UTC, lukasz-galka commented on styles/global.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');
wolalbym miec pobieranie fontu w `Head`

2022-01-21 13:41 UTC, closed without merging